from django.core.management.base import BaseCommand
from quiz.models import Question, Choice, Subject

QUESTIONS = [
    ("What does CSS stand for?", [
        ("Cascading Style Sheets", True),
        ("Computer Style Sheets", False),
        ("Creative Style Sheets", False),
        ("Colorful Style Sheets", False),
    ]),
    ("Which property is used to change the background color?", [
        ("background-color", True),
        ("color", False),
        ("bgcolor", False),
        ("background", False),
    ]),
    ("How do you select an element with id 'demo'?", [
        ("#demo", True),
        (".demo", False),
        ("demo", False),
        ("*demo", False),
    ]),
    ("Which CSS property controls the text size?", [
        ("font-size", True),
        ("text-size", False),
        ("font-style", False),
        ("text-style", False),
    ]),
    ("What is the correct CSS syntax to make all the <p> elements bold?", [
        ("p {font-weight: bold;}", True),
        ("p {text-size: bold;}", False),
        ("<p style='font-size: bold;'>", False),
        ("p {bold: true;}", False),
    ]),
    ("How do you make each word in a text start with a capital letter?", [
        ("text-transform: capitalize", True),
        ("text-transform: uppercase", False),
        ("text-transform: lowercase", False),
        ("text-transform: capitalize-first", False),
    ]),
    ("Which property is used to change the font of an element?", [
        ("font-family", True),
        ("font-style", False),
        ("font-weight", False),
        ("font-size", False),
    ]),
    ("How do you make a list that lists its items with squares?", [
        ("list-style-type: square", True),
        ("list-type: square", False),
        ("list-style: square", False),
        ("list-marker: square", False),
    ]),
    ("What is the correct CSS syntax for making all the <p> elements bold?", [
        ("p {font-weight: bold;}", True),
        ("p {text-size: bold;}", False),
        ("<p style='font-size: bold;'>", False),
        ("p {bold: true;}", False),
    ]),
    ("Which property is used to set the spacing between lines?", [
        ("line-height", True),
        ("letter-spacing", False),
        ("word-spacing", False),
        ("text-spacing", False),
    ]),
    ("How do you select elements with class name 'test'?", [
        (".test", True),
        ("#test", False),
        ("test", False),
        ("*test", False),
    ]),
    ("What is the default value of the position property?", [
        ("static", True),
        ("relative", False),
        ("absolute", False),
        ("fixed", False),
    ]),
    ("Which CSS property is used to control the layout of elements?", [
        ("display", True),
        ("position", False),
        ("float", False),
        ("clear", False),
    ]),
    ("How do you make text italic?", [
        ("font-style: italic", True),
        ("font-weight: italic", False),
        ("text-style: italic", False),
        ("font-italic: true", False),
    ]),
    ("What does the 'z-index' property do?", [
        ("Sets the stack order of elements", True),
        ("Sets the zoom level", False),
        ("Sets the z-axis rotation", False),
        ("Sets the zoom index", False),
    ]),
    ("Which property is used to create space around elements?", [
        ("margin", True),
        ("padding", False),
        ("border", False),
        ("spacing", False),
    ]),
    ("How do you center a block element horizontally?", [
        ("margin: auto", True),
        ("text-align: center", False),
        ("align: center", False),
        ("center: true", False),
    ]),
    ("What is the correct way to include an external CSS file?", [
        ("<link rel='stylesheet' href='styles.css'>", True),
        ("<style src='styles.css'>", False),
        ("<css href='styles.css'>", False),
        ("<link href='styles.css'>", False),
    ]),
    ("Which property is used to set the width of an element?", [
        ("width", True),
        ("height", False),
        ("size", False),
        ("length", False),
    ]),
    ("How do you make text underlined?", [
        ("text-decoration: underline", True),
        ("font-decoration: underline", False),
        ("text-style: underline", False),
        ("underline: true", False),
    ]),
    ("What is the box model in CSS?", [
        ("A model that describes the layout of elements", True),
        ("A model for creating boxes", False),
        ("A model for text boxes", False),
        ("A model for image boxes", False),
    ]),
    ("Which property is used to set the height of an element?", [
        ("height", True),
        ("width", False),
        ("size", False),
        ("length", False),
    ]),
    ("How do you hide an element?", [
        ("display: none", True),
        ("visibility: hidden", False),
        ("opacity: 0", False),
        ("hide: true", False),
    ]),
    ("What is the correct CSS syntax to change the color of text?", [
        ("color: red", True),
        ("text-color: red", False),
        ("font-color: red", False),
        ("red: color", False),
    ]),
    ("Which property is used to set the border of an element?", [
        ("border", True),
        ("outline", False),
        ("margin", False),
        ("padding", False),
    ]),
    ("How do you make text bold?", [
        ("font-weight: bold", True),
        ("font-style: bold", False),
        ("text-weight: bold", False),
        ("bold: true", False),
    ]),
    ("What is the difference between margin and padding?", [
        ("Margin is outside the border, padding is inside", True),
        ("Margin is inside the border, padding is outside", False),
        ("They are the same", False),
        ("Margin affects text, padding affects background", False),
    ]),
    ("Which property is used to set the opacity of an element?", [
        ("opacity", True),
        ("transparent", False),
        ("visibility", False),
        ("alpha", False),
    ]),
    ("How do you create a flexbox container?", [
        ("display: flex", True),
        ("display: block", False),
        ("display: inline", False),
        ("flex: true", False),
    ]),
    ("What is the correct way to write a CSS comment?", [
        ("/* comment */", True),
        ("// comment", False),
        ("<!-- comment -->", False),
        ("# comment", False),
    ]),
    ("Which property is used to set the background image?", [
        ("background-image", True),
        ("image", False),
        ("bg-image", False),
        ("background", False),
    ]),
    ("How do you make an element float to the right?", [
        ("float: right", True),
        ("align: right", False),
        ("position: right", False),
        ("right: true", False),
    ]),
    ("What is the default value of the display property?", [
        ("block", True),
        ("inline", False),
        ("flex", False),
        ("none", False),
    ]),
    ("Which property is used to set the text alignment?", [
        ("text-align", True),
        ("align", False),
        ("text-position", False),
        ("alignment", False),
    ]),
    ("How do you create a grid container?", [
        ("display: grid", True),
        ("display: flex", False),
        ("grid: true", False),
        ("display: block", False),
    ]),
    ("What is the correct CSS syntax to select all elements?", [
        ("*", True),
        ("all", False),
        ("every", False),
        ("element", False),
    ]),
    ("Which property is used to set the border radius?", [
        ("border-radius", True),
        ("border-corner", False),
        ("corner-radius", False),
        ("radius", False),
    ]),
    ("How do you make text blink?", [
        ("animation: blink", True),
        ("text-decoration: blink", False),
        ("blink: true", False),
        ("font-style: blink", False),
    ]),
    ("What is the correct way to set the font size to 20px?", [
        ("font-size: 20px", True),
        ("text-size: 20px", False),
        ("size: 20px", False),
        ("font: 20px", False),
    ]),
    ("Which property is used to set the box shadow?", [
        ("box-shadow", True),
        ("shadow", False),
        ("box-effect", False),
        ("effect", False),
    ]),
    ("How do you make a list without bullets?", [
        ("list-style-type: none", True),
        ("list-style: none", False),
        ("bullet: none", False),
        ("list: none", False),
    ]),
    ("What is the correct CSS syntax to change the cursor?", [
        ("cursor: pointer", True),
        ("pointer: cursor", False),
        ("mouse: pointer", False),
        ("cursor-style: pointer", False),
    ]),
    ("Which property is used to set the transition?", [
        ("transition", True),
        ("animation", False),
        ("transform", False),
        ("effect", False),
    ]),
    ("How do you make an element sticky?", [
        ("position: sticky", True),
        ("position: fixed", False),
        ("position: absolute", False),
        ("sticky: true", False),
    ]),
    ("What is the correct way to set the max-width?", [
        ("max-width: 100px", True),
        ("width-max: 100px", False),
        ("max: 100px", False),
        ("width: max 100px", False),
    ]),
    ("Which property is used to set the text shadow?", [
        ("text-shadow", True),
        ("shadow", False),
        ("text-effect", False),
        ("effect", False),
    ]),
    ("How do you make text uppercase?", [
        ("text-transform: uppercase", True),
        ("font-transform: uppercase", False),
        ("uppercase: true", False),
        ("text-style: uppercase", False),
    ]),
    ("What is the correct CSS syntax to set the line height?", [
        ("line-height: 1.5", True),
        ("height: 1.5", False),
        ("text-height: 1.5", False),
        ("line: 1.5", False),
    ]),
    ("Which property is used to set the overflow?", [
        ("overflow", True),
        ("scroll", False),
        ("hidden", False),
        ("visible", False),
    ]),
    ("How do you make an element responsive?", [
        ("Use media queries", True),
        ("Use responsive tags", False),
        ("Use auto width", False),
        ("Use flex", False),
    ]),
    ("What is the correct way to set the font weight?", [
        ("font-weight: 400", True),
        ("weight: 400", False),
        ("font: 400", False),
        ("text-weight: 400", False),
    ]),
    ("Which property is used to set the vertical alignment?", [
        ("vertical-align", True),
        ("align-vertical", False),
        ("v-align", False),
        ("alignment", False),
    ]),
    ("How do you create a CSS variable?", [
        ("--variable: value", True),
        ("variable: value", False),
        ("var: value", False),
        ("css-var: value", False),
    ]),
    ("What is the correct CSS syntax to use a variable?", [
        ("var(--variable)", True),
        ("variable", False),
        ("--variable", False),
        ("use(--variable)", False),
    ]),
    ("Which property is used to set the clip path?", [
        ("clip-path", True),
        ("path", False),
        ("clip", False),
        ("shape", False),
    ]),
    ("How do you make an element rotate?", [
        ("transform: rotate(45deg)", True),
        ("rotate: 45deg", False),
        ("angle: 45deg", False),
        ("transform-rotate: 45deg", False),
    ]),
    ("What is the correct way to set the background size?", [
        ("background-size: cover", True),
        ("size: cover", False),
        ("bg-size: cover", False),
        ("background: cover", False),
    ]),
    ("Which property is used to set the filter?", [
        ("filter", True),
        ("effect", False),
        ("blur", False),
        ("opacity", False),
    ]),
    ("How do you make text wrap?", [
        ("word-wrap: break-word", True),
        ("wrap: break-word", False),
        ("text-wrap: break-word", False),
        ("break-word: true", False),
    ]),
    ("What is the correct CSS syntax to set the column count?", [
        ("column-count: 3", True),
        ("columns: 3", False),
        ("count: 3", False),
        ("column: 3", False),
    ]),
    ("Which property is used to set the perspective?", [
        ("perspective", True),
        ("3d", False),
        ("depth", False),
        ("view", False),
    ]),
    ("How do you make an element scale?", [
        ("transform: scale(1.5)", True),
        ("scale: 1.5", False),
        ("size: 1.5", False),
        ("transform-scale: 1.5", False),
    ]),
    ("What is the correct way to set the border image?", [
        ("border-image: url(image.png)", True),
        ("image: url(image.png)", False),
        ("border: url(image.png)", False),
        ("bg-border: url(image.png)", False),
    ]),
    ("Which property is used to set the animation?", [
        ("animation", True),
        ("move", False),
        ("transition", False),
        ("effect", False),
    ]),
    ("How do you make text lowercase?", [
        ("text-transform: lowercase", True),
        ("font-transform: lowercase", False),
        ("lowercase: true", False),
        ("text-style: lowercase", False),
    ]),
    ("What is the correct CSS syntax to set the flex direction?", [
        ("flex-direction: column", True),
        ("direction: column", False),
        ("flex: column", False),
        ("column: true", False),
    ]),
    ("Which property is used to set the grid template?", [
        ("grid-template", True),
        ("template", False),
        ("grid", False),
        ("layout", False),
    ]),
    ("How do you make an element absolute positioned?", [
        ("position: absolute", True),
        ("absolute: true", False),
        ("pos: absolute", False),
        ("position-absolute: true", False),
    ]),
    ("What is the correct way to set the text indent?", [
        ("text-indent: 20px", True),
        ("indent: 20px", False),
        ("text: 20px", False),
        ("margin-left: 20px", False),
    ]),
    ("Which property is used to set the letter spacing?", [
        ("letter-spacing", True),
        ("spacing", False),
        ("text-spacing", False),
        ("font-spacing", False),
    ]),
    ("How do you make a background fixed?", [
        ("background-attachment: fixed", True),
        ("attachment: fixed", False),
        ("bg-fixed: true", False),
        ("background: fixed", False),
    ]),
    ("What is the correct CSS syntax to set the outline?", [
        ("outline: 1px solid black", True),
        ("border: 1px solid black", False),
        ("line: 1px solid black", False),
        ("edge: 1px solid black", False),
    ]),
    ("Which property is used to set the resize?", [
        ("resize", True),
        ("size", False),
        ("adjust", False),
        ("change", False),
    ]),
    ("How do you make text justified?", [
        ("text-align: justify", True),
        ("justify: true", False),
        ("align: justify", False),
        ("text-justify: true", False),
    ]),
    ("What is the correct way to set the word spacing?", [
        ("word-spacing: 5px", True),
        ("spacing: 5px", False),
        ("text-spacing: 5px", False),
        ("font-spacing: 5px", False),
    ]),
    ("Which property is used to set the counter?", [
        ("counter", True),
        ("count", False),
        ("number", False),
        ("increment", False),
    ]),
    ("How do you make an element draggable?", [
        ("No CSS property for that", True),
        ("draggable: true", False),
        ("drag: true", False),
        ("move: true", False),
    ]),
    ("What is the correct CSS syntax to set the content?", [
        ("content: 'text'", True),
        ("text: 'text'", False),
        ("add: 'text'", False),
        ("insert: 'text'", False),
    ]),
    ("Which property is used to set the quotes?", [
        ("quotes", True),
        ("quote", False),
        ("quotation", False),
        ("mark", False),
    ]),
    ("How do you make a table cell span multiple columns?", [
        ("colspan", True),
        ("span", False),
        ("column-span", False),
        ("multi-column", False),
    ]),
    ("What is the correct way to set the table layout?", [
        ("table-layout: fixed", True),
        ("layout: fixed", False),
        ("table: fixed", False),
        ("fixed: true", False),
    ]),
    ("Which property is used to set the caption side?", [
        ("caption-side", True),
        ("side", False),
        ("caption", False),
        ("position", False),
    ]),
    ("How do you make a list numbered?", [
        ("list-style-type: decimal", True),
        ("list-type: decimal", False),
        ("number: true", False),
        ("list: decimal", False),
    ]),
    ("What is the correct CSS syntax to set the page break?", [
        ("page-break-before: always", True),
        ("break: always", False),
        ("page: always", False),
        ("before: always", False),
    ]),
    ("Which property is used to set the orphans?", [
        ("orphans", True),
        ("orphan", False),
        ("line", False),
        ("break", False),
    ]),
    ("How do you make text hyphenated?", [
        ("hyphens: auto", True),
        ("hyphen: auto", False),
        ("text-hyphen: auto", False),
        ("auto: true", False),
    ]),
    ("What is the correct way to set the writing mode?", [
        ("writing-mode: vertical-rl", True),
        ("mode: vertical-rl", False),
        ("writing: vertical-rl", False),
        ("vertical: true", False),
    ]),
    ("Which property is used to set the text orientation?", [
        ("text-orientation", True),
        ("orientation", False),
        ("text-direction", False),
        ("direction", False),
    ]),
    ("How do you make an element scrollable?", [
        ("overflow: scroll", True),
        ("scroll: true", False),
        ("overflow-scroll: true", False),
        ("scrollable: true", False),
    ]),
    ("What is the correct CSS syntax to set the user select?", [
        ("user-select: none", True),
        ("select: none", False),
        ("user: none", False),
        ("none: true", False),
    ]),
    ("Which property is used to set the pointer events?", [
        ("pointer-events", True),
        ("events", False),
        ("pointer", False),
        ("mouse", False),
    ]),
    ("How do you make a background gradient?", [
        ("background: linear-gradient(red, blue)", True),
        ("gradient: red to blue", False),
        ("bg-gradient: red blue", False),
        ("background-gradient: red blue", False),
    ]),
    ("What is the correct way to set the border collapse?", [
        ("border-collapse: collapse", True),
        ("collapse: true", False),
        ("border: collapse", False),
        ("table-border: collapse", False),
    ]),
    ("Which property is used to set the empty cells?", [
        ("empty-cells", True),
        ("cells", False),
        ("empty", False),
        ("hide", False),
    ]),
    ("How do you make a table row group?", [
        ("<tbody>", True),
        ("<tr>", False),
        ("<td>", False),
        ("<table>", False),
    ]),
    ("What is the correct CSS syntax to set the speak?", [
        ("speak: none", True),
        ("voice: none", False),
        ("audio: none", False),
        ("sound: none", False),
    ]),
    ("Which property is used to set the volume?", [
        ("volume", True),
        ("sound", False),
        ("audio", False),
        ("voice", False),
    ]),
    ("How do you make text ruby?", [
        ("ruby", True),
        ("text-ruby", False),
        ("ruby-text", False),
        ("annotation", False),
    ]),
    ("What is the correct way to set the marquee?", [
        ("No standard property", True),
        ("marquee: slide", False),
        ("scroll: true", False),
        ("move: true", False),
    ]),
    ("Which property is used to set the nav?", [
        ("nav", True),
        ("navigation", False),
        ("menu", False),
        ("list", False),
    ]),
    ("How do you make an element focusable?", [
        ("tabindex", True),
        ("focus: true", False),
        ("focusable: true", False),
        ("tab: true", False),
    ]),
]


class Command(BaseCommand):
    help = 'Seed 100 CSS-related questions into the quiz app (idempotent)'

    def handle(self, *args, **options):
        created = 0
        css_subj, _ = Subject.objects.get_or_create(name='CSS')
        # Remove existing CSS questions
        Question.objects.filter(subject=css_subj).delete()
        for q_text, choices in QUESTIONS:
            q = Question.objects.create(text=q_text, subject=css_subj)
            created += 1
            # create choices
            for choice_text, is_correct in choices:
                Choice.objects.create(question=q, text=choice_text, is_correct=is_correct)
        self.stdout.write(self.style.SUCCESS(f'Successfully seeded {created} CSS questions.'))
