from django.core.management.base import BaseCommand
from quiz.models import Question, Choice, Subject

QUESTIONS = [
    ("What is the unit of force?", [
        ("Newton", True),
        ("Joule", False),
        ("Watt", False),
        ("Pascal", False),
    ]),
    ("Which of the following is a vector quantity?", [
        ("Velocity", True),
        ("Speed", False),
        ("Mass", False),
        ("Temperature", False),
    ]),
    ("The SI unit of electric current is?", [
        ("Ampere", True),
        ("Volt", False),
        ("Ohm", False),
        ("Coulomb", False),
    ]),
    ("What is the chemical formula for water?", [
        ("H2O", True),
        ("HO2", False),
        ("H3O", False),
        ("OH2", False),
    ]),
    ("Which gas is produced during photosynthesis?", [
        ("Oxygen", True),
        ("Carbon dioxide", False),
        ("Nitrogen", False),
        ("Hydrogen", False),
    ]),
    ("The pH of pure water is?", [
        ("7", True),
        ("0", False),
        ("14", False),
        ("1", False),
    ]),
    ("What is the atomic number of carbon?", [
        ("6", True),
        ("8", False),
        ("12", False),
        ("14", False),
    ]),
    ("Which organelle is known as the powerhouse of the cell?", [
        ("Mitochondria", True),
        ("Nucleus", False),
        ("Ribosome", False),
        ("Golgi apparatus", False),
    ]),
    ("The speed of light in vacuum is?", [
        ("3 × 10^8 m/s", True),
        ("3 × 10^6 m/s", False),
        ("3 × 10^10 m/s", False),
        ("3 × 10^4 m/s", False),
    ]),
    ("Which element has the highest electronegativity?", [
        ("Fluorine", True),
        ("Chlorine", False),
        ("Bromine", False),
        ("Iodine", False),
    ]),
    ("What is the process by which plants make their own food?", [
        ("Photosynthesis", True),
        ("Respiration", False),
        ("Transpiration", False),
        ("Evaporation", False),
    ]),
    ("The unit of power is?", [
        ("Watt", True),
        ("Joule", False),
        ("Newton", False),
        ("Pascal", False),
    ]),
    ("Which of the following is a noble gas?", [
        ("Helium", True),
        ("Oxygen", False),
        ("Nitrogen", False),
        ("Carbon", False),
    ]),
    ("What is the basic unit of life?", [
        ("Cell", True),
        ("Tissue", False),
        ("Organ", False),
        ("System", False),
    ]),
    ("The law of conservation of energy states that?", [
        ("Energy can neither be created nor destroyed", True),
        ("Energy can be created but not destroyed", False),
        ("Energy can be destroyed but not created", False),
        ("Energy can be both created and destroyed", False),
    ]),
    ("Which acid is present in vinegar?", [
        ("Acetic acid", True),
        ("Citric acid", False),
        ("Sulfuric acid", False),
        ("Hydrochloric acid", False),
    ]),
    ("What is the function of red blood cells?", [
        ("Carry oxygen", True),
        ("Fight infection", False),
        ("Clot blood", False),
        ("Produce antibodies", False),
    ]),
    ("The SI unit of pressure is?", [
        ("Pascal", True),
        ("Newton", False),
        ("Joule", False),
        ("Watt", False),
    ]),
    ("Which of the following is a monosaccharide?", [
        ("Glucose", True),
        ("Sucrose", False),
        ("Lactose", False),
        ("Maltose", False),
    ]),
    ("What is the chemical symbol for sodium?", [
        ("Na", True),
        ("So", False),
        ("Sd", False),
        ("Nm", False),
    ]),
    ("Which part of the plant is responsible for photosynthesis?", [
        ("Leaf", True),
        ("Root", False),
        ("Stem", False),
        ("Flower", False),
    ]),
    ("The atomic mass of hydrogen is?", [
        ("1 u", True),
        ("2 u", False),
        ("4 u", False),
        ("16 u", False),
    ]),
    ("What is the SI unit of energy?", [
        ("Joule", True),
        ("Watt", False),
        ("Newton", False),
        ("Pascal", False),
    ]),
    ("Which gas is known as laughing gas?", [
        ("Nitrous oxide", True),
        ("Carbon dioxide", False),
        ("Oxygen", False),
        ("Nitrogen", False),
    ]),
    ("What is the process of conversion of water vapor into water?", [
        ("Condensation", True),
        ("Evaporation", False),
        ("Sublimation", False),
        ("Melting", False),
    ]),
    ("The unit of frequency is?", [
        ("Hertz", True),
        ("Watt", False),
        ("Volt", False),
        ("Ampere", False),
    ]),
    ("Which of the following is a strong acid?", [
        ("Hydrochloric acid", True),
        ("Acetic acid", False),
        ("Carbonic acid", False),
        ("Phosphoric acid", False),
    ]),
    ("What is the function of the heart?", [
        ("Pump blood", True),
        ("Digest food", False),
        ("Produce hormones", False),
        ("Filter waste", False),
    ]),
    ("The speed of sound in air is approximately?", [
        ("343 m/s", True),
        ("300 m/s", False),
        ("400 m/s", False),
        ("500 m/s", False),
    ]),
    ("Which element is essential for the formation of chlorophyll?", [
        ("Magnesium", True),
        ("Iron", False),
        ("Calcium", False),
        ("Potassium", False),
    ]),
    ("What is the chemical formula for carbon dioxide?", [
        ("CO2", True),
        ("CO", False),
        ("C2O", False),
        ("C2O2", False),
    ]),
    ("Which of the following is a vector quantity?", [
        ("Displacement", True),
        ("Distance", False),
        ("Speed", False),
        ("Time", False),
    ]),
    ("The pH of blood is?", [
        ("7.4", True),
        ("7", False),
        ("6.8", False),
        ("8", False),
    ]),
    ("What is the atomic number of oxygen?", [
        ("8", True),
        ("6", False),
        ("10", False),
        ("12", False),
    ]),
    ("Which organ is responsible for filtering blood?", [
        ("Kidney", True),
        ("Liver", False),
        ("Heart", False),
        ("Lung", False),
    ]),
    ("The SI unit of electric charge is?", [
        ("Coulomb", True),
        ("Volt", False),
        ("Ampere", False),
        ("Ohm", False),
    ]),
    ("Which of the following is a hydrocarbon?", [
        ("Methane", True),
        ("Water", False),
        ("Ammonia", False),
        ("Carbon dioxide", False),
    ]),
    ("What is the process by which plants lose water?", [
        ("Transpiration", True),
        ("Photosynthesis", False),
        ("Respiration", False),
        ("Evaporation", False),
    ]),
    ("The unit of work is?", [
        ("Joule", True),
        ("Watt", False),
        ("Newton", False),
        ("Pascal", False),
    ]),
    ("Which gas is produced during respiration?", [
        ("Carbon dioxide", True),
        ("Oxygen", False),
        ("Nitrogen", False),
        ("Hydrogen", False),
    ]),
    ("What is the chemical symbol for potassium?", [
        ("K", True),
        ("P", False),
        ("Po", False),
        ("Pt", False),
    ]),
    ("Which of the following is a prokaryotic cell?", [
        ("Bacteria", True),
        ("Plant cell", False),
        ("Animal cell", False),
        ("Fungal cell", False),
    ]),
    ("The acceleration due to gravity on Earth is?", [
        ("9.8 m/s²", True),
        ("10 m/s²", False),
        ("9.81 m/s²", False),
        ("8.9 m/s²", False),
    ]),
    ("Which acid is present in lemon?", [
        ("Citric acid", True),
        ("Acetic acid", False),
        ("Tartaric acid", False),
        ("Malic acid", False),
    ]),
    ("What is the function of white blood cells?", [
        ("Fight infection", True),
        ("Carry oxygen", False),
        ("Clot blood", False),
        ("Produce antibodies", False),
    ]),
    ("The SI unit of temperature is?", [
        ("Kelvin", True),
        ("Celsius", False),
        ("Fahrenheit", False),
        ("Rankine", False),
    ]),
    ("Which of the following is a disaccharide?", [
        ("Sucrose", True),
        ("Glucose", False),
        ("Fructose", False),
        ("Galactose", False),
    ]),
    ("What is the chemical symbol for calcium?", [
        ("Ca", True),
        ("C", False),
        ("Cl", False),
        ("Cu", False),
    ]),
    ("Which part of the eye is responsible for focusing light?", [
        ("Lens", True),
        ("Retina", False),
        ("Cornea", False),
        ("Iris", False),
    ]),
    ("The atomic mass of carbon is?", [
        ("12 u", True),
        ("6 u", False),
        ("14 u", False),
        ("16 u", False),
    ]),
    ("What is the SI unit of magnetic field?", [
        ("Tesla", True),
        ("Gauss", False),
        ("Weber", False),
        ("Henry", False),
    ]),
    ("Which gas is used in photosynthesis?", [
        ("Carbon dioxide", True),
        ("Oxygen", False),
        ("Nitrogen", False),
        ("Hydrogen", False),
    ]),
    ("What is the pH of a neutral solution?", [
        ("7", True),
        ("0", False),
        ("14", False),
        ("1", False),
    ]),
    ("The atomic number of hydrogen is?", [
        ("1", True),
        ("2", False),
        ("3", False),
        ("4", False),
    ]),
    ("Which organelle contains digestive enzymes?", [
        ("Lysosome", True),
        ("Mitochondria", False),
        ("Ribosome", False),
        ("Golgi apparatus", False),
    ]),
    ("The speed of light in glass is?", [
        ("2 × 10^8 m/s", True),
        ("3 × 10^8 m/s", False),
        ("1.5 × 10^8 m/s", False),
        ("2.5 × 10^8 m/s", False),
    ]),
    ("Which element has the highest atomic radius?", [
        ("Cesium", True),
        ("Lithium", False),
        ("Sodium", False),
        ("Potassium", False),
    ]),
    ("What is the process of conversion of solid to gas?", [
        ("Sublimation", True),
        ("Melting", False),
        ("Evaporation", False),
        ("Condensation", False),
    ]),
    ("The unit of resistance is?", [
        ("Ohm", True),
        ("Volt", False),
        ("Ampere", False),
        ("Coulomb", False),
    ]),
    ("Which of the following is a weak acid?", [
        ("Acetic acid", True),
        ("Hydrochloric acid", False),
        ("Sulfuric acid", False),
        ("Nitric acid", False),
    ]),
    ("What is the function of the liver?", [
        ("Detoxify blood", True),
        ("Pump blood", False),
        ("Produce insulin", False),
        ("Filter air", False),
    ]),
    ("The wavelength of visible light ranges from?", [
        ("400-700 nm", True),
        ("100-400 nm", False),
        ("700-1000 nm", False),
        ("1-10 nm", False),
    ]),
    ("Which element is used in the formation of bones?", [
        ("Calcium", True),
        ("Iron", False),
        ("Magnesium", False),
        ("Potassium", False),
    ]),
    ("What is the chemical formula for methane?", [
        ("CH4", True),
        ("C2H6", False),
        ("C3H8", False),
        ("C4H10", False),
    ]),
    ("Which of the following is a scalar quantity?", [
        ("Mass", True),
        ("Velocity", False),
        ("Acceleration", False),
        ("Force", False),
    ]),
    ("The pH of stomach acid is?", [
        ("2", True),
        ("7", False),
        ("9", False),
        ("11", False),
    ]),
    ("What is the atomic number of nitrogen?", [
        ("7", True),
        ("6", False),
        ("8", False),
        ("9", False),
    ]),
    ("Which organ is responsible for producing insulin?", [
        ("Pancreas", True),
        ("Liver", False),
        ("Kidney", False),
        ("Heart", False),
    ]),
    ("The SI unit of capacitance is?", [
        ("Farad", True),
        ("Henry", False),
        ("Tesla", False),
        ("Siemens", False),
    ]),
    ("Which of the following is an alkene?", [
        ("Ethene", True),
        ("Ethane", False),
        ("Ethyne", False),
        ("Methane", False),
    ]),
    ("What is the process by which animals obtain energy?", [
        ("Respiration", True),
        ("Photosynthesis", False),
        ("Transpiration", False),
        ("Evaporation", False),
    ]),
    ("The unit of inductance is?", [
        ("Henry", True),
        ("Farad", False),
        ("Tesla", False),
        ("Siemens", False),
    ]),
    ("Which gas is used in fire extinguishers?", [
        ("Carbon dioxide", True),
        ("Oxygen", False),
        ("Nitrogen", False),
        ("Hydrogen", False),
    ]),
    ("What is the chemical symbol for magnesium?", [
        ("Mg", True),
        ("Mn", False),
        ("Mo", False),
        ("Ma", False),
    ]),
    ("Which of the following is a eukaryotic cell?", [
        ("Plant cell", True),
        ("Bacteria", False),
        ("Virus", False),
        ("Fungi", False),
    ]),
    ("The acceleration due to gravity on Moon is?", [
        ("1.6 m/s²", True),
        ("9.8 m/s²", False),
        ("3.7 m/s²", False),
        ("0 m/s²", False),
    ]),
    ("Which acid is present in milk?", [
        ("Lactic acid", True),
        ("Acetic acid", False),
        ("Citric acid", False),
        ("Tartaric acid", False),
    ]),
    ("What is the function of platelets?", [
        ("Clot blood", True),
        ("Carry oxygen", False),
        ("Fight infection", False),
        ("Produce hormones", False),
    ]),
    ("The SI unit of luminous intensity is?", [
        ("Candela", True),
        ("Lumen", False),
        ("Lux", False),
        ("Watt", False),
    ]),
    ("Which of the following is a polysaccharide?", [
        ("Starch", True),
        ("Glucose", False),
        ("Sucrose", False),
        ("Fructose", False),
    ]),
    ("What is the chemical symbol for iron?", [
        ("Fe", True),
        ("I", False),
        ("Ir", False),
        ("In", False),
    ]),
    ("Which part of the brain controls balance?", [
        ("Cerebellum", True),
        ("Cerebrum", False),
        ("Medulla", False),
        ("Pons", False),
    ]),
    ("The atomic mass of oxygen is?", [
        ("16 u", True),
        ("8 u", False),
        ("14 u", False),
        ("18 u", False),
    ]),
    ("What is the SI unit of conductance?", [
        ("Siemens", True),
        ("Ohm", False),
        ("Volt", False),
        ("Ampere", False),
    ]),
    ("Which gas is produced during fermentation?", [
        ("Carbon dioxide", True),
        ("Oxygen", False),
        ("Nitrogen", False),
        ("Hydrogen", False),
    ]),
    ("What is the pH of a basic solution?", [
        ("Above 7", True),
        ("7", False),
        ("Below 7", False),
        ("0", False),
    ]),
    ("The atomic number of helium is?", [
        ("2", True),
        ("1", False),
        ("3", False),
        ("4", False),
    ]),
    ("Which organelle is responsible for protein synthesis?", [
        ("Ribosome", True),
        ("Mitochondria", False),
        ("Nucleus", False),
        ("Lysosome", False),
    ]),
    ("The speed of sound in water is?", [
        ("1500 m/s", True),
        ("343 m/s", False),
        ("300 m/s", False),
        ("500 m/s", False),
    ]),
    ("Which element has the lowest electronegativity?", [
        ("Cesium", True),
        ("Fluorine", False),
        ("Chlorine", False),
        ("Bromine", False),
    ]),
    ("What is the process of conversion of gas to liquid?", [
        ("Condensation", True),
        ("Sublimation", False),
        ("Melting", False),
        ("Freezing", False),
    ]),
    ("The unit of electric potential is?", [
        ("Volt", True),
        ("Ampere", False),
        ("Ohm", False),
        ("Coulomb", False),
    ]),
    ("Which of the following is a base?", [
        ("Sodium hydroxide", True),
        ("Hydrochloric acid", False),
        ("Acetic acid", False),
        ("Sulfuric acid", False),
    ]),
    ("What is the function of the spleen?", [
        ("Filter blood", True),
        ("Pump blood", False),
        ("Produce bile", False),
        ("Store urine", False),
    ]),
    ("The Planck's constant is?", [
        ("6.626 × 10^-34 J s", True),
        ("1.602 × 10^-19 C", False),
        ("9.109 × 10^-31 kg", False),
        ("1.381 × 10^-23 J/K", False),
    ]),
    ("Which element is used in the formation of hemoglobin?", [
        ("Iron", True),
        ("Calcium", False),
        ("Magnesium", False),
        ("Potassium", False),
    ]),
    ("What is the chemical formula for ammonia?", [
        ("NH3", True),
        ("N2H4", False),
        ("NH4OH", False),
        ("N2O", False),
    ]),
    ("Which of the following is a vector quantity?", [
        ("Acceleration", True),
        ("Mass", False),
        ("Volume", False),
        ("Density", False),
    ]),
    ("The pH of saliva is?", [
        ("6.5-7.5", True),
        ("2", False),
        ("9", False),
        ("11", False),
    ]),
    ("What is the atomic number of sodium?", [
        ("11", True),
        ("10", False),
        ("12", False),
        ("13", False),
    ]),
    ("Which organ is responsible for producing bile?", [
        ("Liver", True),
        ("Pancreas", False),
        ("Gallbladder", False),
        ("Stomach", False),
    ]),
    ("The SI unit of inductance is?", [
        ("Henry", True),
        ("Farad", False),
        ("Tesla", False),
        ("Siemens", False),
    ]),
    ("Which of the following is an alkyne?", [
        ("Ethyne", True),
        ("Ethene", False),
        ("Ethane", False),
        ("Methane", False),
    ]),
    ("What is the process by which plants take in water?", [
        ("Absorption", True),
        ("Photosynthesis", False),
        ("Respiration", False),
        ("Transpiration", False),
    ]),
    ("The unit of luminous flux is?", [
        ("Lumen", True),
        ("Candela", False),
        ("Lux", False),
        ("Watt", False),
    ]),
    ("Which gas is used in welding?", [
        ("Acetylene", True),
        ("Oxygen", False),
        ("Nitrogen", False),
        ("Hydrogen", False),
    ]),
    ("What is the chemical symbol for zinc?", [
        ("Zn", True),
        ("Z", False),
        ("Zi", False),
        ("Ze", False),
    ]),
    ("Which of the following is a virus?", [
        ("HIV", True),
        ("Bacteria", False),
        ("Fungi", False),
        ("Protozoa", False),
    ]),
    ("The acceleration due to gravity on Jupiter is?", [
        ("23.1 m/s²", True),
        ("9.8 m/s²", False),
        ("3.7 m/s²", False),
        ("1.6 m/s²", False),
    ]),
    ("Which acid is present in ant sting?", [
        ("Formic acid", True),
        ("Acetic acid", False),
        ("Citric acid", False),
        ("Hydrochloric acid", False),
    ]),
    ("What is the function of lymph nodes?", [
        ("Filter lymph", True),
        ("Produce blood", False),
        ("Store fat", False),
        ("Produce hormones", False),
    ]),
    ("The SI unit of illuminance is?", [
        ("Lux", True),
        ("Lumen", False),
        ("Candela", False),
        ("Watt", False),
    ]),
    ("Which of the following is a lipid?", [
        ("Triglyceride", True),
        ("Glucose", False),
        ("Amino acid", False),
        ("Nucleotide", False),
    ]),
    ("What is the chemical symbol for copper?", [
        ("Cu", True),
        ("C", False),
        ("Co", False),
        ("Cp", False),
    ]),
    ("Which part of the nervous system controls involuntary actions?", [
        ("Autonomic nervous system", True),
        ("Central nervous system", False),
        ("Peripheral nervous system", False),
        ("Somatic nervous system", False),
    ]),
    ("The atomic mass of nitrogen is?", [
        ("14 u", True),
        ("7 u", False),
        ("15 u", False),
        ("16 u", False),
    ]),
    ("What is the SI unit of torque?", [
        ("Newton meter", True),
        ("Joule", False),
        ("Watt", False),
        ("Pascal", False),
    ]),
    ("Which gas is produced during rusting?", [
        ("None", True),
        ("Oxygen", False),
        ("Hydrogen", False),
        ("Carbon dioxide", False),
    ]),
    ("What is the pH of an acidic solution?", [
        ("Below 7", True),
        ("7", False),
        ("Above 7", False),
        ("14", False),
    ]),
    ("The atomic number of lithium is?", [
        ("3", True),
        ("1", False),
        ("2", False),
        ("4", False),
    ]),
    ("Which organelle is responsible for cell division?", [
        ("Centriole", True),
        ("Mitochondria", False),
        ("Ribosome", False),
        ("Golgi apparatus", False),
    ]),
    ("The speed of sound in steel is?", [
        ("5000 m/s", True),
        ("343 m/s", False),
        ("1500 m/s", False),
        ("300 m/s", False),
    ]),
    ("Which element has the highest ionization energy?", [
        ("Helium", True),
        ("Neon", False),
        ("Argon", False),
        ("Krypton", False),
    ]),
    ("What is the process of conversion of liquid to gas?", [
        ("Evaporation", True),
        ("Condensation", False),
        ("Sublimation", False),
        ("Melting", False),
    ]),
    ("The unit of electric field is?", [
        ("Volt per meter", True),
        ("Tesla", False),
        ("Henry", False),
        ("Farad", False),
    ]),
    ("Which of the following is a salt?", [
        ("Sodium chloride", True),
        ("Hydrochloric acid", False),
        ("Sodium hydroxide", False),
        ("Water", False),
    ]),
    ("What is the function of the thyroid gland?", [
        ("Produce hormones", True),
        ("Pump blood", False),
        ("Filter blood", False),
        ("Digest food", False),
    ]),
    ("The Boltzmann constant is?", [
        ("1.381 × 10^-23 J/K", True),
        ("6.626 × 10^-34 J s", False),
        ("1.602 × 10^-19 C", False),
        ("9.109 × 10^-31 kg", False),
    ]),
    ("Which element is used in the formation of DNA?", [
        ("Phosphorus", True),
        ("Calcium", False),
        ("Magnesium", False),
        ("Potassium", False),
    ]),
    ("What is the chemical formula for sulfuric acid?", [
        ("H2SO4", True),
        ("HCl", False),
        ("HNO3", False),
        ("H3PO4", False),
    ]),
    ("Which of the following is a scalar quantity?", [
        ("Energy", True),
        ("Momentum", False),
        ("Torque", False),
        ("Angular velocity", False),
    ]),
    ("The pH of urine is?", [
        ("4.5-8", True),
        ("2", False),
        ("7", False),
        ("11", False),
    ]),
    ("What is the atomic number of potassium?", [
        ("19", True),
        ("18", False),
        ("20", False),
        ("21", False),
    ]),
    ("Which organ is responsible for producing urine?", [
        ("Kidney", True),
        ("Bladder", False),
        ("Urethra", False),
        ("Ureter", False),
    ]),
    ("The SI unit of magnetic flux is?", [
        ("Weber", True),
        ("Tesla", False),
        ("Henry", False),
        ("Farad", False),
    ]),
    ("Which of the following is an ester?", [
        ("Ethyl acetate", True),
        ("Ethanol", False),
        ("Acetic acid", False),
        ("Methane", False),
    ]),
    ("What is the process by which plants reproduce?", [
        ("Pollination", True),
        ("Fertilization", False),
        ("Germination", False),
        ("Photosynthesis", False),
    ]),
    ("The unit of angular momentum is?", [
        ("Kilogram meter squared per second", True),
        ("Joule", False),
        ("Watt", False),
        ("Pascal", False),
    ]),
    ("Which gas is used in balloons?", [
        ("Helium", True),
        ("Hydrogen", False),
        ("Oxygen", False),
        ("Nitrogen", False),
    ]),
    ("What is the chemical symbol for silver?", [
        ("Ag", True),
        ("A", False),
        ("Au", False),
        ("Al", False),
    ]),
    ("Which of the following is a protozoa?", [
        ("Amoeba", True),
        ("Bacteria", False),
        ("Virus", False),
        ("Fungi", False),
    ]),
    ("The acceleration due to gravity on Mars is?", [
        ("3.7 m/s²", True),
        ("9.8 m/s²", False),
        ("1.6 m/s²", False),
        ("23.1 m/s²", False),
    ]),
    ("Which acid is present in tomato?", [
        ("Oxalic acid", True),
        ("Citric acid", False),
        ("Acetic acid", False),
        ("Malic acid", False),
    ]),
    ("What is the function of the pituitary gland?", [
        ("Control other glands", True),
        ("Pump blood", False),
        ("Filter blood", False),
        ("Produce insulin", False),
    ]),
    ("The SI unit of angular velocity is?", [
        ("Radian per second", True),
        ("Joule", False),
        ("Watt", False),
        ("Pascal", False),
    ]),
    ("Which of the following is a protein?", [
        ("Hemoglobin", True),
        ("Glucose", False),
        ("Starch", False),
        ("Triglyceride", False),
    ]),
    ("What is the chemical symbol for gold?", [
        ("Au", True),
        ("Ag", False),
        ("Fe", False),
        ("Cu", False),
    ]),
    ("Which part of the brain controls breathing?", [
        ("Medulla oblongata", True),
        ("Cerebellum", False),
        ("Cerebrum", False),
        ("Pons", False),
    ]),
    ("The atomic mass of sodium is?", [
        ("23 u", True),
        ("11 u", False),
        ("24 u", False),
        ("22 u", False),
    ]),
    ("What is the SI unit of impulse?", [
        ("Newton second", True),
        ("Joule", False),
        ("Watt", False),
        ("Pascal", False),
    ]),
    ("Which gas is produced during electrolysis of water?", [
        ("Hydrogen and Oxygen", True),
        ("Carbon dioxide", False),
        ("Nitrogen", False),
        ("Chlorine", False),
    ]),
    ("What is the pH of seawater?", [
        ("8.1", True),
        ("7", False),
        ("6", False),
        ("9", False),
    ]),
    ("The atomic number of beryllium is?", [
        ("4", True),
        ("2", False),
        ("3", False),
        ("5", False),
    ]),
    ("Which organelle is responsible for photosynthesis?", [
        ("Chloroplast", True),
        ("Mitochondria", False),
        ("Ribosome", False),
        ("Golgi apparatus", False),
    ]),
    ("The speed of sound in air at 0°C is?", [
        ("331 m/s", True),
        ("343 m/s", False),
        ("300 m/s", False),
        ("400 m/s", False),
    ]),
    ("Which element has the lowest atomic radius?", [
        ("Helium", True),
        ("Neon", False),
        ("Argon", False),
        ("Krypton", False),
    ]),
    ("What is the process of conversion of solid to liquid?", [
        ("Melting", True),
        ("Freezing", False),
        ("Evaporation", False),
        ("Condensation", False),
    ]),
    ("The unit of electric dipole moment is?", [
        ("Coulomb meter", True),
        ("Tesla", False),
        ("Henry", False),
        ("Farad", False),
    ]),
    ("Which of the following is an oxide?", [
        ("Carbon dioxide", True),
        ("Hydrochloric acid", False),
        ("Sodium hydroxide", False),
        ("Sodium chloride", False),
    ]),
    ("What is the function of the adrenal gland?", [
        ("Produce adrenaline", True),
        ("Pump blood", False),
        ("Filter blood", False),
        ("Produce bile", False),
    ]),
    ("The Avogadro's number is?", [
        ("6.022 × 10^23", True),
        ("3.1416", False),
        ("1.602 × 10^-19", False),
        ("9.8", False),
    ]),
    ("Which element is used in the formation of chlorophyll?", [
        ("Magnesium", True),
        ("Iron", False),
        ("Calcium", False),
        ("Potassium", False),
    ]),
    ("What is the chemical formula for nitric acid?", [
        ("HNO3", True),
        ("HCl", False),
        ("H2SO4", False),
        ("H3PO4", False),
    ]),
    ("Which of the following is a vector quantity?", [
        ("Force", True),
        ("Work", False),
        ("Power", False),
        ("Energy", False),
    ]),
    ("The pH of milk is?", [
        ("6.5", True),
        ("7", False),
        ("4", False),
        ("9", False),
    ]),
    ("What is the atomic number of magnesium?", [
        ("12", True),
        ("10", False),
        ("11", False),
        ("13", False),
    ]),
    ("Which organ is responsible for producing RBC?", [
        ("Bone marrow", True),
        ("Liver", False),
        ("Kidney", False),
        ("Spleen", False),
    ]),
    ("The SI unit of electric dipole moment is?", [
        ("Coulomb meter", True),
        ("Tesla", False),
        ("Henry", False),
        ("Farad", False),
    ]),
    ("Which of the following is an aldehyde?", [
        ("Formaldehyde", True),
        ("Acetone", False),
        ("Ethanol", False),
        ("Acetic acid", False),
    ]),
    ("What is the process by which seeds germinate?", [
        ("Germination", True),
        ("Pollination", False),
        ("Fertilization", False),
        ("Photosynthesis", False),
    ]),
    ("The unit of momentum is?", [
        ("Kilogram meter per second", True),
        ("Joule", False),
        ("Watt", False),
        ("Pascal", False),
    ]),
    ("Which gas is used in refrigerators?", [
        ("Freon", True),
        ("Oxygen", False),
        ("Nitrogen", False),
        ("Hydrogen", False),
    ]),
    ("What is the chemical symbol for mercury?", [
        ("Hg", True),
        ("H", False),
        ("He", False),
        ("Ho", False),
    ]),
    ("Which of the following is a fungus?", [
        ("Mushroom", True),
        ("Bacteria", False),
        ("Virus", False),
        ("Protozoa", False),
    ]),
    ("The acceleration due to gravity on Venus is?", [
        ("8.87 m/s²", True),
        ("9.8 m/s²", False),
        ("3.7 m/s²", False),
        ("1.6 m/s²", False),
    ]),
    ("Which acid is present in sour milk?", [
        ("Lactic acid", True),
        ("Citric acid", False),
        ("Acetic acid", False),
        ("Tartaric acid", False),
    ]),
    ("What is the function of the parathyroid gland?", [
        ("Regulate calcium", True),
        ("Produce insulin", False),
        ("Control thyroid", False),
        ("Produce adrenaline", False),
    ]),
    ("The SI unit of luminous flux is?", [
        ("Lumen", True),
        ("Candela", False),
        ("Lux", False),
        ("Watt", False),
    ]),
    ("Which of the following is a nucleic acid?", [
        ("DNA", True),
        ("Glucose", False),
        ("Amino acid", False),
        ("Fatty acid", False),
    ]),
    ("What is the chemical symbol for lead?", [
        ("Pb", True),
        ("P", False),
        ("Pd", False),
        ("Pt", False),
    ]),
    ("Which part of the brain controls vision?", [
        ("Occipital lobe", True),
        ("Frontal lobe", False),
        ("Temporal lobe", False),
        ("Parietal lobe", False),
    ]),
    ("The atomic mass of potassium is?", [
        ("39 u", True),
        ("19 u", False),
        ("40 u", False),
        ("38 u", False),
    ]),
    ("What is the SI unit of angular acceleration?", [
        ("Radian per second squared", True),
        ("Joule", False),
        ("Watt", False),
        ("Pascal", False),
    ]),
    ("Which gas is produced during combustion?", [
        ("Carbon dioxide", True),
        ("Oxygen", False),
        ("Nitrogen", False),
        ("Hydrogen", False),
    ]),
    ("What is the pH of baking soda solution?", [
        ("8.5", True),
        ("7", False),
        ("5", False),
        ("2", False),
    ]),
    ("The atomic number of calcium is?", [
        ("20", True),
        ("18", False),
        ("19", False),
        ("21", False),
    ]),
    ("Which organelle is responsible for storage?", [
        ("Vacuole", True),
        ("Mitochondria", False),
        ("Ribosome", False),
        ("Golgi apparatus", False),
    ]),
    ("The speed of sound in hydrogen is?", [
        ("1284 m/s", True),
        ("343 m/s", False),
        ("1500 m/s", False),
        ("500 m/s", False),
    ]),
    ("Which element has the highest melting point?", [
        ("Tungsten", True),
        ("Iron", False),
        ("Gold", False),
        ("Silver", False),
    ]),
    ("What is the process of conversion of liquid to solid?", [
        ("Freezing", True),
        ("Melting", False),
        ("Evaporation", False),
        ("Condensation", False),
    ]),
    ("The unit of electric flux is?", [
        ("Volt meter", True),
        ("Tesla", False),
        ("Henry", False),
        ("Farad", False),
    ]),
    ("Which of the following is a hydroxide?", [
        ("Sodium hydroxide", True),
        ("Hydrochloric acid", False),
        ("Sodium chloride", False),
        ("Water", False),
    ]),
    ("What is the function of the pineal gland?", [
        ("Produce melatonin", True),
        ("Pump blood", False),
        ("Filter blood", False),
        ("Produce bile", False),
    ]),
]


class Command(BaseCommand):
    help = 'Seed 100 NEET-related questions into the quiz app (idempotent)'

    def handle(self, *args, **options):
        created = 0
        neet_subj, _ = Subject.objects.get_or_create(name='NEET')
        # Remove existing NEET questions
        Question.objects.filter(subject=neet_subj).delete()
        for q_text, choices in QUESTIONS:
            q = Question.objects.create(text=q_text, subject=neet_subj)
            created += 1
            # create choices
            for choice_text, is_correct in choices:
                Choice.objects.create(question=q, text=choice_text, is_correct=is_correct)
        self.stdout.write(self.style.SUCCESS(f'Successfully seeded {created} NEET questions.'))
