from django.core.management.base import BaseCommand
from quiz.models import Question, Choice, Subject

QUESTIONS = [
    ("What does HTML stand for?", [
        ("Hyper Text Markup Language", True),
        ("High Tech Modern Language", False),
        ("Hyperlink and Text Markup Language", False),
        ("Home Tool Markup Language", False),
    ]),
    ("Who is making the Web standards?", [
        ("The World Wide Web Consortium", True),
        ("Mozilla", False),
        ("Microsoft", False),
        ("Google", False),
    ]),
    ("Choose the correct HTML element for the largest heading:", [
        ("<h1>", True),
        ("<h6>", False),
        ("<heading>", False),
        ("<head>", False),
    ]),
    ("What is the correct HTML element for inserting a line break?", [
        ("<br>", True),
        ("<lb>", False),
        ("<break>", False),
        ("<newline>", False),
    ]),
    ("What is the correct HTML for adding a background color?", [
        ("<body style='background-color:yellow;'>", True),
        ("<background>yellow</background>", False),
        ("<body bg='yellow'>", False),
        ("<body background='yellow'>", False),
    ]),
    ("Choose the correct HTML element to define important text:", [
        ("<strong>", True),
        ("<b>", False),
        ("<i>", False),
        ("<important>", False),
    ]),
    ("Choose the correct HTML element to define emphasized text:", [
        ("<em>", True),
        ("<i>", False),
        ("<italic>", False),
        ("<emphasize>", False),
    ]),
    ("What is the correct HTML for creating a hyperlink?", [
        ("<a href='http://www.w3schools.com'>W3Schools</a>", True),
        ("<a>http://www.w3schools.com</a>", False),
        ("<a url='http://www.w3schools.com'>W3Schools</a>", False),
        ("<a name='http://www.w3schools.com'>W3Schools</a>", False),
    ]),
    ("Which character is used to indicate an end tag?", [
        ("/", True),
        ("*", False),
        ("^", False),
        ("<", False),
    ]),
    ("How can you open a link in a new tab/browser window?", [
        ("<a href='url' target='_blank'>", True),
        ("<a href='url' new>", False),
        ("<a href='url' target='new'>", False),
        ("<a href='url' open>", False),
    ]),
    ("Which of these elements are all <table> elements?", [
        ("<table><tr><td>", True),
        ("<table><head><tfoot>", False),
        ("<table><tr><tt>", False),
        ("<thead><body><tr>", False),
    ]),
    ("Inline elements are normally displayed without starting a new line.", [
        ("True", True),
        ("False", False),
        ("Depends on the browser", False),
        ("Only in tables", False),
    ]),
    ("How can you make a numbered list?", [
        ("<ol>", True),
        ("<ul>", False),
        ("<dl>", False),
        ("<list>", False),
    ]),
    ("How can you make a bulleted list?", [
        ("<ul>", True),
        ("<ol>", False),
        ("<dl>", False),
        ("<list>", False),
    ]),
    ("What is the correct HTML for making a checkbox?", [
        ("<input type='checkbox'>", True),
        ("<checkbox>", False),
        ("<input type='check'>", False),
        ("<check>", False),
    ]),
    ("What is the correct HTML for making a text input field?", [
        ("<input type='text'>", True),
        ("<input type='textfield'>", False),
        ("<textfield>", False),
        ("<textinput>", False),
    ]),
    ("What is the correct HTML for making a drop-down list?", [
        ("<select>", True),
        ("<list>", False),
        ("<dropdown>", False),
        ("<input type='dropdown'>", False),
    ]),
    ("What is the correct HTML for making a text area?", [
        ("<textarea>", True),
        ("<input type='textarea'>", False),
        ("<input type='textbox'>", False),
        ("<textbox>", False),
    ]),
    ("What is the correct HTML for inserting an image?", [
        ("<img src='image.gif' alt='MyImage'>", True),
        ("<image src='image.gif' alt='MyImage'>", False),
        ("<img href='image.gif' alt='MyImage'>", False),
        ("<img alt='MyImage'>image.gif</img>", False),
    ]),
    ("What is the correct HTML for inserting a background image?", [
        ("<body background='background.gif'>", True),
        ("<body bg='background.gif'>", False),
        ("<background img='background.gif'>", False),
        ("<body style='background-image:url(background.gif)'>", False),
    ]),
    ("<canvas> is only a container for graphics.", [
        ("True", True),
        ("False", False),
        ("Only for images", False),
        ("Only for text", False),
    ]),
    ("What does CSS stand for?", [
        ("Cascading Style Sheets", True),
        ("Creative Style Sheets", False),
        ("Computer Style Sheets", False),
        ("Colorful Style Sheets", False),
    ]),
    ("Where in an HTML document is the correct place to refer to an external style sheet?", [
        ("In the <head> section", True),
        ("In the <body> section", False),
        ("At the end of the document", False),
        ("In the <title> section", False),
    ]),
    ("Which HTML tag is used to define an internal style sheet?", [
        ("<style>", True),
        ("<css>", False),
        ("<script>", False),
        ("<link>", False),
    ]),
    ("Which HTML attribute is used to define inline styles?", [
        ("style", True),
        ("styles", False),
        ("class", False),
        ("font", False),
    ]),
    ("Which is the correct CSS syntax?", [
        ("body {color: black;}", True),
        ("{body:color=black;}", False),
        ("body:color=black;", False),
        ("body {color= black;}", False),
    ]),
    ("How do you insert a comment in a CSS file?", [
        ("/* this is a comment */", True),
        ("// this is a comment //", False),
        ("<!-- this is a comment -->", False),
        ("# this is a comment #", False),
    ]),
    ("Which property is used to change the background color?", [
        ("background-color", True),
        ("bgcolor", False),
        ("color", False),
        ("background", False),
    ]),
    ("How do you add a background color for all <h1> elements?", [
        ("h1 {background-color:#FFFFFF;}", True),
        ("all.h1 {background-color:#FFFFFF;}", False),
        ("h1.all {background-color:#FFFFFF;}", False),
        ("h1 {bgcolor:#FFFFFF;}", False),
    ]),
    ("Which CSS property is used to change the text color of an element?", [
        ("color", True),
        ("fgcolor", False),
        ("text-color", False),
        ("font-color", False),
    ]),
    ("Which CSS property controls the text size?", [
        ("font-size", True),
        ("text-size", False),
        ("font-style", False),
        ("text-style", False),
    ]),
    ("What is the correct CSS syntax for making all the <p> elements bold?", [
        ("p {font-weight:bold;}", True),
        ("<p style='font-size:bold;'>", False),
        ("p {text-size:bold;}", False),
        ("p {font:bold;}", False),
    ]),
    ("How do you display hyperlinks without an underline?", [
        ("a {text-decoration:none;}", True),
        ("a {decoration:no-underline;}", False),
        ("a {text-decoration:no-underline;}", False),
        ("a {underline:none;}", False),
    ]),
    ("How do you make each word in a text start with a capital letter?", [
        ("text-transform:capitalize", True),
        ("You can't do that with CSS", False),
        ("transform:capitalize", False),
        ("font-transform:capitalize", False),
    ]),
    ("Which property is used to change the font of an element?", [
        ("font-family", True),
        ("font", False),
        ("font-style", False),
        ("font-weight", False),
    ]),
    ("How do you make the text bold?", [
        ("font-weight:bold", True),
        ("style:bold", False),
        ("font:bold", False),
        ("bold:true", False),
    ]),
    ("Which property is used to change the left margin of an element?", [
        ("margin-left", True),
        ("indent", False),
        ("margin", False),
        ("padding-left", False),
    ]),
    ("When using the padding property; are you allowed to use negative values?", [
        ("No", True),
        ("Yes", False),
        ("Depends on the browser", False),
        ("Only for top and bottom", False),
    ]),
    ("How do you make a list that lists its items with squares?", [
        ("list-style-type: square", True),
        ("list-type: square", False),
        ("list-style: square", False),
        ("li {square}", False),
    ]),
    ("The # symbol specifies that the selector is?", [
        ("id", True),
        ("class", False),
        ("tag", False),
        ("universal", False),
    ]),
    ("The . symbol specifies that the selector is?", [
        ("class", True),
        ("id", False),
        ("tag", False),
        ("universal", False),
    ]),
    ("What is the correct HTML for referring to an external style sheet?", [
        ("<link rel='stylesheet' type='text/css' href='mystyle.css'>", True),
        ("<stylesheet>mystyle.css</stylesheet>", False),
        ("<style src='mystyle.css'>", False),
        ("<link href='mystyle.css'>", False),
    ]),
    ("Where in an HTML document is the correct place to refer to an external style sheet?", [
        ("In the <head> section", True),
        ("In the <body> section", False),
        ("At the top of the document", False),
        ("Before the </html> tag", False),
    ]),
    ("Which HTML tag is used to define an internal style sheet?", [
        ("<style>", True),
        ("<script>", False),
        ("<css>", False),
        ("<link>", False),
    ]),
    ("Which HTML attribute is used to define inline styles?", [
        ("style", True),
        ("class", False),
        ("styles", False),
        ("font", False),
    ]),
    ("Which is the correct CSS syntax?", [
        ("body {color: black;}", True),
        ("body:color=black;", False),
        ("{body;color:black;}", False),
        ("body {color=black;}", False),
    ]),
    ("How do you insert a comment in a CSS file?", [
        ("/* this is a comment */", True),
        ("// this is a comment", False),
        ("<!-- this is a comment -->", False),
        ("# this is a comment", False),
    ]),
    ("Which property is used to change the background color?", [
        ("background-color", True),
        ("bgcolor", False),
        ("color", False),
        ("background", False),
    ]),
    ("How do you add a background color for all <h1> elements?", [
        ("h1 {background-color:#FFFFFF;}", True),
        ("h1.all {background-color:#FFFFFF;}", False),
        ("all.h1 {background-color:#FFFFFF;}", False),
        ("h1 {bgcolor:#FFFFFF;}", False),
    ]),
    ("Which CSS property is used to change the text color of an element?", [
        ("color", True),
        ("fgcolor", False),
        ("text-color", False),
        ("font-color", False),
    ]),
    ("Which CSS property controls the text size?", [
        ("font-size", True),
        ("text-size", False),
        ("font-style", False),
        ("text-style", False),
    ]),
    ("What is the correct CSS syntax for making all the <p> elements bold?", [
        ("p {font-weight:bold;}", True),
        ("p {text-size:bold;}", False),
        ("<p style='font-size:bold;'>", False),
        ("p {font:bold;}", False),
    ]),
    ("How do you display hyperlinks without an underline?", [
        ("a {text-decoration:none;}", True),
        ("a {text-decoration:no-underline;}", False),
        ("a {underline:none;}", False),
        ("a {decoration:no-underline;}", False),
    ]),
    ("How do you make each word in a text start with a capital letter?", [
        ("text-transform:capitalize", True),
        ("transform:capitalize", False),
        ("font-transform:capitalize", False),
        ("You can't do that with CSS", False),
    ]),
    ("Which property is used to change the font of an element?", [
        ("font-family", True),
        ("font", False),
        ("font-style", False),
        ("font-weight", False),
    ]),
    ("How do you make the text bold?", [
        ("font-weight:bold", True),
        ("style:bold", False),
        ("font:bold", False),
        ("bold:true", False),
    ]),
    ("Which property is used to change the left margin of an element?", [
        ("margin-left", True),
        ("indent", False),
        ("margin", False),
        ("padding-left", False),
    ]),
    ("When using the padding property; are you allowed to use negative values?", [
        ("No", True),
        ("Yes", False),
        ("Depends on the browser", False),
        ("Only for top and bottom", False),
    ]),
    ("How do you make a list that lists its items with squares?", [
        ("list-style-type: square", True),
        ("list-type: square", False),
        ("list-style: square", False),
        ("li {square}", False),
    ]),
    ("The # symbol specifies that the selector is?", [
        ("id", True),
        ("class", False),
        ("tag", False),
        ("universal", False),
    ]),
    ("The . symbol specifies that the selector is?", [
        ("class", True),
        ("id", False),
        ("tag", False),
        ("universal", False),
    ]),
    ("What is the correct HTML for referring to an external style sheet?", [
        ("<link rel='stylesheet' type='text/css' href='mystyle.css'>", True),
        ("<stylesheet>mystyle.css</stylesheet>", False),
        ("<style src='mystyle.css'>", False),
        ("<link href='mystyle.css'>", False),
    ]),
    ("Where in an HTML document is the correct place to refer to an external style sheet?", [
        ("In the <head> section", True),
        ("In the <body> section", False),
        ("At the top of the document", False),
        ("Before the </html> tag", False),
    ]),
    ("Which HTML tag is used to define an internal style sheet?", [
        ("<style>", True),
        ("<script>", False),
        ("<css>", False),
        ("<link>", False),
    ]),
    ("Which HTML attribute is used to define inline styles?", [
        ("style", True),
        ("class", False),
        ("styles", False),
        ("font", False),
    ]),
    ("Which is the correct CSS syntax?", [
        ("body {color: black;}", True),
        ("body:color=black;", False),
        ("{body;color:black;}", False),
        ("body {color=black;}", False),
    ]),
    ("How do you insert a comment in a CSS file?", [
        ("/* this is a comment */", True),
        ("// this is a comment", False),
        ("<!-- this is a comment -->", False),
        ("# this is a comment", False),
    ]),
    ("Which property is used to change the background color?", [
        ("background-color", True),
        ("bgcolor", False),
        ("color", False),
        ("background", False),
    ]),
    ("How do you add a background color for all <h1> elements?", [
        ("h1 {background-color:#FFFFFF;}", True),
        ("h1.all {background-color:#FFFFFF;}", False),
        ("all.h1 {background-color:#FFFFFF;}", False),
        ("h1 {bgcolor:#FFFFFF;}", False),
    ]),
    ("Which CSS property is used to change the text color of an element?", [
        ("color", True),
        ("fgcolor", False),
        ("text-color", False),
        ("font-color", False),
    ]),
    ("Which CSS property controls the text size?", [
        ("font-size", True),
        ("text-size", False),
        ("font-style", False),
        ("text-style", False),
    ]),
    ("What is the correct CSS syntax for making all the <p> elements bold?", [
        ("p {font-weight:bold;}", True),
        ("p {text-size:bold;}", False),
        ("<p style='font-size:bold;'>", False),
        ("p {font:bold;}", False),
    ]),
    ("How do you display hyperlinks without an underline?", [
        ("a {text-decoration:none;}", True),
        ("a {text-decoration:no-underline;}", False),
        ("a {underline:none;}", False),
        ("a {decoration:no-underline;}", False),
    ]),
    ("How do you make each word in a text start with a capital letter?", [
        ("text-transform:capitalize", True),
        ("transform:capitalize", False),
        ("font-transform:capitalize", False),
        ("You can't do that with CSS", False),
    ]),
    ("Which property is used to change the font of an element?", [
        ("font-family", True),
        ("font", False),
        ("font-style", False),
        ("font-weight", False),
    ]),
    ("How do you make the text bold?", [
        ("font-weight:bold", True),
        ("style:bold", False),
        ("font:bold", False),
        ("bold:true", False),
    ]),
    ("Which property is used to change the left margin of an element?", [
        ("margin-left", True),
        ("indent", False),
        ("margin", False),
        ("padding-left", False),
    ]),
    ("When using the padding property; are you allowed to use negative values?", [
        ("No", True),
        ("Yes", False),
        ("Depends on the browser", False),
        ("Only for top and bottom", False),
    ]),
    ("How do you make a list that lists its items with squares?", [
        ("list-style-type: square", True),
        ("list-type: square", False),
        ("list-style: square", False),
        ("li {square}", False),
    ]),
    ("The # symbol specifies that the selector is?", [
        ("id", True),
        ("class", False),
        ("tag", False),
        ("universal", False),
    ]),
    ("The . symbol specifies that the selector is?", [
        ("class", True),
        ("id", False),
        ("tag", False),
        ("universal", False),
    ]),
    ("What is the correct HTML for referring to an external style sheet?", [
        ("<link rel='stylesheet' type='text/css' href='mystyle.css'>", True),
        ("<stylesheet>mystyle.css</stylesheet>", False),
        ("<style src='mystyle.css'>", False),
        ("<link href='mystyle.css'>", False),
    ]),
    ("Where in an HTML document is the correct place to refer to an external style sheet?", [
        ("In the <head> section", True),
        ("In the <body> section", False),
        ("At the top of the document", False),
        ("Before the </html> tag", False),
    ]),
    ("Which HTML tag is used to define an internal style sheet?", [
        ("<style>", True),
        ("<script>", False),
        ("<css>", False),
        ("<link>", False),
    ]),
    ("Which HTML attribute is used to define inline styles?", [
        ("style", True),
        ("class", False),
        ("styles", False),
        ("font", False),
    ]),
    ("Which is the correct CSS syntax?", [
        ("body {color: black;}", True),
        ("body:color=black;", False),
        ("{body;color:black;}", False),
        ("body {color=black;}", False),
    ]),
    ("How do you insert a comment in a CSS file?", [
        ("/* this is a comment */", True),
        ("// this is a comment", False),
        ("<!-- this is a comment -->", False),
        ("# this is a comment", False),
    ]),
    ("Which property is used to change the background color?", [
        ("background-color", True),
        ("bgcolor", False),
        ("color", False),
        ("background", False),
    ]),
    ("How do you add a background color for all <h1> elements?", [
        ("h1 {background-color:#FFFFFF;}", True),
        ("h1.all {background-color:#FFFFFF;}", False),
        ("all.h1 {background-color:#FFFFFF;}", False),
        ("h1 {bgcolor:#FFFFFF;}", False),
    ]),
    ("Which CSS property is used to change the text color of an element?", [
        ("color", True),
        ("fgcolor", False),
        ("text-color", False),
        ("font-color", False),
    ]),
    ("Which CSS property controls the text size?", [
        ("font-size", True),
        ("text-size", False),
        ("font-style", False),
        ("text-style", False),
    ]),
    ("What is the correct CSS syntax for making all the <p> elements bold?", [
        ("p {font-weight:bold;}", True),
        ("p {text-size:bold;}", False),
        ("<p style='font-size:bold;'>", False),
        ("p {font:bold;}", False),
    ]),
    ("How do you display hyperlinks without an underline?", [
        ("a {text-decoration:none;}", True),
        ("a {text-decoration:no-underline;}", False),
        ("a {underline:none;}", False),
        ("a {decoration:no-underline;}", False),
    ]),
    ("How do you make each word in a text start with a capital letter?", [
        ("text-transform:capitalize", True),
        ("transform:capitalize", False),
        ("font-transform:capitalize", False),
        ("You can't do that with CSS", False),
    ]),
    ("Which property is used to change the font of an element?", [
        ("font-family", True),
        ("font", False),
        ("font-style", False),
        ("font-weight", False),
    ]),
    ("How do you make the text bold?", [
        ("font-weight:bold", True),
        ("style:bold", False),
        ("font:bold", False),
        ("bold:true", False),
    ]),
    ("Which property is used to change the left margin of an element?", [
        ("margin-left", True),
        ("indent", False),
        ("margin", False),
        ("padding-left", False),
    ]),
    ("When using the padding property; are you allowed to use negative values?", [
        ("No", True),
        ("Yes", False),
        ("Depends on the browser", False),
        ("Only for top and bottom", False),
    ]),
    ("How do you make a list that lists its items with squares?", [
        ("list-style-type: square", True),
        ("list-type: square", False),
        ("list-style: square", False),
        ("li {square}", False),
    ]),
    ("The # symbol specifies that the selector is?", [
        ("id", True),
        ("class", False),
        ("tag", False),
        ("universal", False),
    ]),
    ("The . symbol specifies that the selector is?", [
        ("class", True),
        ("id", False),
        ("tag", False),
        ("universal", False),
    ]),
    ("What is the correct HTML for referring to an external style sheet?", [
        ("<link rel='stylesheet' type='text/css' href='mystyle.css'>", True),
        ("<stylesheet>mystyle.css</stylesheet>", False),
        ("<style src='mystyle.css'>", False),
        ("<link href='mystyle.css'>", False),
    ]),
    ("Where in an HTML document is the correct place to refer to an external style sheet?", [
        ("In the <head> section", True),
        ("In the <body> section", False),
        ("At the top of the document", False),
        ("Before the </html> tag", False),
    ]),
    ("Which HTML tag is used to define an internal style sheet?", [
        ("<style>", True),
        ("<script>", False),
        ("<css>", False),
        ("<link>", False),
    ]),
    ("Which HTML attribute is used to define inline styles?", [
        ("style", True),
        ("class", False),
        ("styles", False),
        ("font", False),
    ]),
    ("Which is the correct CSS syntax?", [
        ("body {color: black;}", True),
        ("body:color=black;", False),
        ("{body;color:black;}", False),
        ("body {color=black;}", False),
    ]),
    ("How do you insert a comment in a CSS file?", [
        ("/* this is a comment */", True),
        ("// this is a comment", False),
        ("<!-- this is a comment -->", False),
        ("# this is a comment", False),
    ]),
    ("Which property is used to change the background color?", [
        ("background-color", True),
        ("bgcolor", False),
        ("color", False),
        ("background", False),
    ]),
    ("How do you add a background color for all <h1> elements?", [
        ("h1 {background-color:#FFFFFF;}", True),
        ("h1.all {background-color:#FFFFFF;}", False),
        ("all.h1 {background-color:#FFFFFF;}", False),
        ("h1 {bgcolor:#FFFFFF;}", False),
    ]),
    ("Which CSS property is used to change the text color of an element?", [
        ("color", True),
        ("fgcolor", False),
        ("text-color", False),
        ("font-color", False),
    ]),
    ("Which CSS property controls the text size?", [
        ("font-size", True),
        ("text-size", False),
        ("font-style", False),
        ("text-style", False),
    ]),
    ("What is the correct CSS syntax for making all the <p> elements bold?", [
        ("p {font-weight:bold;}", True),
        ("p {text-size:bold;}", False),
        ("<p style='font-size:bold;'>", False),
        ("p {font:bold;}", False),
    ]),
    ("How do you display hyperlinks without an underline?", [
        ("a {text-decoration:none;}", True),
        ("a {text-decoration:no-underline;}", False),
        ("a {underline:none;}", False),
        ("a {decoration:no-underline;}", False),
    ]),
    ("How do you make each word in a text start with a capital letter?", [
        ("text-transform:capitalize", True),
        ("transform:capitalize", False),
        ("font-transform:capitalize", False),
        ("You can't do that with CSS", False),
    ]),
    ("Which property is used to change the font of an element?", [
        ("font-family", True),
        ("font", False),
        ("font-style", False),
        ("font-weight", False),
    ]),
    ("How do you make the text bold?", [
        ("font-weight:bold", True),
        ("style:bold", False),
        ("font:bold", False),
        ("bold:true", False),
    ]),
    ("Which property is used to change the left margin of an element?", [
        ("margin-left", True),
        ("indent", False),
        ("margin", False),
        ("padding-left", False),
    ]),
    ("When using the padding property; are you allowed to use negative values?", [
        ("No", True),
        ("Yes", False),
        ("Depends on the browser", False),
        ("Only for top and bottom", False),
    ]),
    ("How do you make a list that lists its items with squares?", [
        ("list-style-type: square", True),
        ("list-type: square", False),
        ("list-style: square", False),
        ("li {square}", False),
    ]),
    ("The # symbol specifies that the selector is?", [
        ("id", True),
        ("class", False),
        ("tag", False),
        ("universal", False),
    ]),
    ("The . symbol specifies that the selector is?", [
        ("class", True),
        ("id", False),
        ("tag", False),
        ("universal", False),
    ]),
]


class Command(BaseCommand):
    help = 'Seed 100 HTML-related questions into the quiz app (idempotent)'

    def handle(self, *args, **options):
        created = 0
        html_subj, _ = Subject.objects.get_or_create(name='HTML')
        # Remove existing HTML questions
        Question.objects.filter(subject=html_subj).delete()
        for q_text, choices in QUESTIONS:
            q = Question.objects.create(text=q_text, subject=html_subj)
            created += 1
            # create choices
            for choice_text, is_correct in choices:
                Choice.objects.create(question=q, text=choice_text, is_correct=is_correct)
        self.stdout.write(self.style.SUCCESS(f'Successfully seeded {created} HTML questions.'))
