from django.core.management.base import BaseCommand
from quiz.models import Question, Choice, Subject

QUESTIONS = [
    ("What is Python?", [
        ("A programming language", True),
        ("A snake", False),
        ("A database", False),
        ("An operating system", False),
    ]),
    ("Who created Python?", [
        ("Guido van Rossum", True),
        ("Dennis Ritchie", False),
        ("James Gosling", False),
        ("Bjarne Stroustrup", False),
    ]),
    ("What is the file extension for Python files?", [
        (".py", True),
        (".python", False),
        (".p", False),
        (".pyth", False),
    ]),
    ("How do you print 'Hello World' in Python?", [
        ("print('Hello World')", True),
        ("echo 'Hello World'", False),
        ("console.log('Hello World')", False),
        ("printf('Hello World')", False),
    ]),
    ("What is the correct way to declare a variable in Python?", [
        ("x = 5", True),
        ("int x = 5", False),
        ("var x = 5", False),
        ("x := 5", False),
    ]),
    ("Which of the following is a mutable data type in Python?", [
        ("List", True),
        ("Tuple", False),
        ("String", False),
        ("Integer", False),
    ]),
    ("What does 'len()' function do?", [
        ("Returns the length of an object", True),
        ("Returns the type", False),
        ("Returns the sum", False),
        ("Returns the max", False),
    ]),
    ("How do you create a list in Python?", [
        ("my_list = []", True),
        ("my_list = {}", False),
        ("my_list = ()", False),
        ("my_list = <>", False),
    ]),
    ("What is the output of 2 + 3 * 4?", [
        ("14", True),
        ("20", False),
        ("24", False),
        ("10", False),
    ]),
    ("How do you write a comment in Python?", [
        ("# This is a comment", True),
        ("// This is a comment", False),
        ("/* This is a comment */", False),
        ("<!-- This is a comment -->", False),
    ]),
    ("What is the purpose of 'if' statement?", [
        ("To execute code based on condition", True),
        ("To loop", False),
        ("To define function", False),
        ("To import module", False),
    ]),
    ("How do you define a function in Python?", [
        ("def my_function():", True),
        ("function my_function():", False),
        ("func my_function():", False),
        ("define my_function():", False),
    ]),
    ("What is a tuple in Python?", [
        ("An immutable sequence", True),
        ("A mutable list", False),
        ("A dictionary", False),
        ("A set", False),
    ]),
    ("How do you access the first element of a list?", [
        ("my_list[0]", True),
        ("my_list[1]", False),
        ("my_list.first()", False),
        ("my_list.get(0)", False),
    ]),
    ("What does '==' operator do?", [
        ("Checks for equality", True),
        ("Assigns value", False),
        ("Checks for identity", False),
        ("Compares types", False),
    ]),
    ("How do you import a module?", [
        ("import module_name", True),
        ("include module_name", False),
        ("require module_name", False),
        ("using module_name", False),
    ]),
    ("What is the range() function used for?", [
        ("To generate a sequence of numbers", True),
        ("To find range of values", False),
        ("To create a list", False),
        ("To iterate", False),
    ]),
    ("How do you create a dictionary?", [
        ("my_dict = {}", True),
        ("my_dict = []", False),
        ("my_dict = ()", False),
        ("my_dict = <>", False),
    ]),
    ("What is the output of type(5)?", [
        ("<class 'int'>", True),
        ("int", False),
        ("5", False),
        ("<type 'int'>", False),
    ]),
    ("How do you handle exceptions in Python?", [
        ("try-except", True),
        ("try-catch", False),
        ("catch-except", False),
        ("handle-error", False),
    ]),
    ("What is a class in Python?", [
        ("A blueprint for objects", True),
        ("A data type", False),
        ("A function", False),
        ("A module", False),
    ]),
    ("How do you create an object?", [
        ("obj = MyClass()", True),
        ("obj = new MyClass()", False),
        ("obj = MyClass", False),
        ("obj = create MyClass()", False),
    ]),
    ("What is inheritance?", [
        ("A class deriving from another", True),
        ("A function calling another", False),
        ("A variable assigning", False),
        ("A loop nesting", False),
    ]),
    ("How do you open a file?", [
        ("open('file.txt')", True),
        ("file('file.txt')", False),
        ("read('file.txt')", False),
        ("load('file.txt')", False),
    ]),
    ("What is the purpose of 'with' statement?", [
        ("To handle resources", True),
        ("To define function", False),
        ("To loop", False),
        ("To condition", False),
    ]),
    ("How do you convert string to int?", [
        ("int('5')", True),
        ("str(5)", False),
        ("float('5')", False),
        ("convert('5')", False),
    ]),
    ("What is a lambda function?", [
        ("An anonymous function", True),
        ("A named function", False),
        ("A built-in function", False),
        ("A recursive function", False),
    ]),
    ("How do you sort a list?", [
        ("my_list.sort()", True),
        ("sort(my_list)", False),
        ("my_list.order()", False),
        ("arrange(my_list)", False),
    ]),
    ("What is the difference between list and tuple?", [
        ("List is mutable, tuple is not", True),
        ("Tuple is mutable, list is not", False),
        ("They are the same", False),
        ("List is ordered, tuple is not", False),
    ]),
    ("How do you check if key exists in dict?", [
        ("key in my_dict", True),
        ("my_dict.has(key)", False),
        ("my_dict.contains(key)", False),
        ("exists(my_dict, key)", False),
    ]),
    ("What is slicing?", [
        ("Extracting part of sequence", True),
        ("Cutting strings", False),
        ("Dividing numbers", False),
        ("Sorting", False),
    ]),
    ("How do you reverse a list?", [
        ("my_list.reverse()", True),
        ("reverse(my_list)", False),
        ("my_list[::-1]", False),
        ("invert(my_list)", False),
    ]),
    ("What is a set in Python?", [
        ("Unordered collection of unique items", True),
        ("Ordered list", False),
        ("Dictionary", False),
        ("Tuple", False),
    ]),
    ("How do you add to a set?", [
        ("my_set.add(item)", True),
        ("my_set.append(item)", False),
        ("my_set.insert(item)", False),
        ("my_set.push(item)", False),
    ]),
    ("What is the output of bool(0)?", [
        ("False", True),
        ("True", False),
        ("0", False),
        ("None", False),
    ]),
    ("How do you get user input?", [
        ("input()", True),
        ("get()", False),
        ("read()", False),
        ("scan()", False),
    ]),
    ("What is a module?", [
        ("A file containing Python code", True),
        ("A function", False),
        ("A class", False),
        ("A variable", False),
    ]),
    ("How do you install packages?", [
        ("pip install package", True),
        ("python install package", False),
        ("easy_install package", False),
        ("apt install package", False),
    ]),
    ("What is virtual environment?", [
        ("Isolated Python environment", True),
        ("Virtual machine", False),
        ("Online environment", False),
        ("Test environment", False),
    ]),
    ("How do you create venv?", [
        ("python -m venv myenv", True),
        ("venv create myenv", False),
        ("virtualenv myenv", False),
        ("pip venv myenv", False),
    ]),
    ("What is Django?", [
        ("A web framework", True),
        ("A database", False),
        ("A library", False),
        ("An IDE", False),
    ]),
    ("What is Flask?", [
        ("A micro web framework", True),
        ("A database ORM", False),
        ("A testing tool", False),
        ("A package manager", False),
    ]),
    ("What is NumPy?", [
        ("Library for arrays", True),
        ("Web framework", False),
        ("Database", False),
        ("Game engine", False),
    ]),
    ("What is Pandas?", [
        ("Data manipulation library", True),
        ("Web scraper", False),
        ("Machine learning", False),
        ("Visualization", False),
    ]),
    ("What is Matplotlib?", [
        ("Plotting library", True),
        ("3D modeling", False),
        ("Web design", False),
        ("Audio processing", False),
    ]),
    ("What is TensorFlow?", [
        ("Machine learning framework", True),
        ("Database", False),
        ("Web server", False),
        ("Text editor", False),
    ]),
    ("What is PyTorch?", [
        ("Deep learning library", True),
        ("Game framework", False),
        ("Web API", False),
        ("Package installer", False),
    ]),
    ("What is the purpose of __init__.py?", [
        ("Makes directory a package", True),
        ("Initializes variables", False),
        ("Runs on import", False),
        ("Defines main", False),
    ]),
    ("What is a decorator?", [
        ("Modifies function behavior", True),
        ("Decorates output", False),
        ("Styles code", False),
        ("Comments code", False),
    ]),
    ("How do you use a decorator?", [
        ("@decorator\ndef func():", True),
        ("decorator(func)", False),
        ("func.decorator()", False),
        ("decorate func", False),
    ]),
    ("What is list comprehension?", [
        ("Concise way to create lists", True),
        ("Understanding lists", False),
        ("Compressing lists", False),
        ("Sorting lists", False),
    ]),
    ("Example of list comprehension?", [
        ("[x*2 for x in range(5)]", True),
        ("for x in range(5): x*2", False),
        ("list(x*2 for x in range(5))", False),
        ("map(x*2, range(5))", False),
    ]),
    ("What is generator?", [
        ("Function that yields values", True),
        ("Creates objects", False),
        ("Generates random", False),
        ("Builds lists", False),
    ]),
    ("How to create generator?", [
        ("def gen(): yield 1", True),
        ("gen = (1)", False),
        ("gen = [1]", False),
        ("gen = {1}", False),
    ]),
    ("What is *args?", [
        ("Variable positional arguments", True),
        ("Arguments list", False),
        ("Keyword args", False),
        ("Default args", False),
    ]),
    ("What is **kwargs?", [
        ("Variable keyword arguments", True),
        ("Args dictionary", False),
        ("Positional args", False),
        ("Required args", False),
    ]),
    ("What is self in class?", [
        ("Reference to instance", True),
        ("Class reference", False),
        ("Global reference", False),
        ("Method reference", False),
    ]),
    ("What is __str__?", [
        ("String representation", True),
        ("Private method", False),
        ("Constructor", False),
        ("Destructor", False),
    ]),
    ("What is __name__?", [
        ("Module name", True),
        ("Function name", False),
        ("Class name", False),
        ("Variable name", False),
    ]),
    ("What is if __name__ == '__main__'?", [
        ("Runs if script is main", True),
        ("Always runs", False),
        ("Never runs", False),
        ("Runs on import", False),
    ]),
    ("What is pickle?", [
        ("Serialization module", True),
        ("Pickling cucumbers", False),
        ("Data compression", False),
        ("File handling", False),
    ]),
    ("What is JSON?", [
        ("Data interchange format", True),
        ("JavaScript object", False),
        ("Database", False),
        ("Markup language", False),
    ]),
    ("How to parse JSON?", [
        ("json.loads()", True),
        ("json.parse()", False),
        ("parse.json()", False),
        ("load.json()", False),
    ]),
    ("What is threading?", [
        ("Concurrent execution", True),
        ("Sorting", False),
        ("File reading", False),
        ("Web scraping", False),
    ]),
    ("What is multiprocessing?", [
        ("Multiple processes", True),
        ("Multi-threading", False),
        ("Parallel computing", False),
        ("Async programming", False),
    ]),
    ("What is asyncio?", [
        ("Asynchronous programming", True),
        ("Sync programming", False),
        ("File I/O", False),
        ("Web framework", False),
    ]),
    ("What is a coroutine?", [
        ("Async function", True),
        ("Generator", False),
        ("Thread", False),
        ("Process", False),
    ]),
    ("How to use async?", [
        ("async def func():", True),
        ("def async func():", False),
        ("async func():", False),
        ("function async:", False),
    ]),
    ("What is await?", [
        ("Wait for async result", True),
        ("Pause execution", False),
        ("Call function", False),
        ("Define async", False),
    ]),
    ("What is unittest?", [
        ("Testing framework", True),
        ("Unit conversion", False),
        ("Math library", False),
        ("Web server", False),
    ]),
    ("What is pytest?", [
        ("Testing tool", True),
        ("Python installer", False),
        ("Package manager", False),
        ("IDE", False),
    ]),
    ("What is logging?", [
        ("Recording events", True),
        ("User login", False),
        ("Math log", False),
        ("File writing", False),
    ]),
    ("What is sys.argv?", [
        ("Command line arguments", True),
        ("System variables", False),
        ("Environment vars", False),
        ("Module args", False),
    ]),
    ("What is os module?", [
        ("Operating system interface", True),
        ("Online store", False),
        ("Object storage", False),
        ("Open source", False),
    ]),
    ("What is pathlib?", [
        ("Object-oriented filesystem paths", True),
        ("Path finding", False),
        ("URL parsing", False),
        ("Directory listing", False),
    ]),
    ("What is datetime?", [
        ("Date and time handling", True),
        ("Time zone", False),
        ("Calendar", False),
        ("Timer", False),
    ]),
    ("What is random?", [
        ("Random number generation", True),
        ("Random access", False),
        ("Shuffle", False),
        ("Sort", False),
    ]),
    ("What is math?", [
        ("Mathematical functions", True),
        ("Math operations", False),
        ("Calculator", False),
        ("Algebra", False),
    ]),
    ("What is collections?", [
        ("Container datatypes", True),
        ("Data collection", False),
        ("Garbage collection", False),
        ("List operations", False),
    ]),
    ("What is itertools?", [
        ("Iterator functions", True),
        ("Iteration tools", False),
        ("Infinite loops", False),
        ("Loop control", False),
    ]),
    ("What is functools?", [
        ("Higher-order functions", True),
        ("Function tools", False),
        ("Decorators", False),
        ("Recursion", False),
    ]),
    ("What is operator?", [
        ("Function versions of operators", True),
        ("Math operators", False),
        ("Comparison ops", False),
        ("Assignment ops", False),
    ]),
    ("What is re?", [
        ("Regular expressions", True),
        ("Reverse", False),
        ("Repeat", False),
        ("Replace", False),
    ]),
    ("What is urllib?", [
        ("URL handling", True),
        ("Web scraping", False),
        ("HTTP requests", False),
        ("Email", False),
    ]),
    ("What is requests?", [
        ("HTTP library", True),
        ("Request handling", False),
        ("API calls", False),
        ("Web server", False),
    ]),
    ("What is BeautifulSoup?", [
        ("HTML parser", True),
        ("Web framework", False),
        ("CSS framework", False),
        ("JavaScript library", False),
    ]),
    ("What is Selenium?", [
        ("Web automation", True),
        ("Database", False),
        ("Testing", False),
        ("Scraping", False),
    ]),
    ("What is SQLite?", [
        ("Embedded database", True),
        ("Web database", False),
        ("NoSQL", False),
        ("Cloud storage", False),
    ]),
    ("What is SQLAlchemy?", [
        ("ORM for databases", True),
        ("SQL parser", False),
        ("Query builder", False),
        ("Database server", False),
    ]),
    ("What is PostgreSQL?", [
        ("Relational database", True),
        ("NoSQL", False),
        ("Key-value store", False),
        ("Document DB", False),
    ]),
    ("What is MongoDB?", [
        ("NoSQL document database", True),
        ("Relational DB", False),
        ("Graph DB", False),
        ("Time series DB", False),
    ]),
    ("What is Redis?", [
        ("In-memory data structure store", True),
        ("Cache", False),
        ("Database", False),
        ("Message queue", False),
    ]),
    ("What is Docker?", [
        ("Containerization platform", True),
        ("Virtual machine", False),
        ("Web server", False),
        ("Package manager", False),
    ]),
    ("What is Kubernetes?", [
        ("Container orchestration", True),
        ("Container runtime", False),
        ("Monitoring", False),
        ("Logging", False),
    ]),
    ("What is Git?", [
        ("Version control system", True),
        ("Text editor", False),
        ("IDE", False),
        ("Compiler", False),
    ]),
    ("What is GitHub?", [
        ("Code hosting platform", True),
        ("IDE", False),
        ("Compiler", False),
        ("Package manager", False),
    ]),
    ("What is CI/CD?", [
        ("Continuous Integration/Deployment", True),
        ("Code editor", False),
        ("Testing framework", False),
        ("Documentation", False),
    ]),
    ("What is API?", [
        ("Application Programming Interface", True),
        ("Application Process Interface", False),
        ("Automated Programming Interface", False),
        ("Advanced Python Interface", False),
    ]),
    ("What is REST?", [
        ("Representational State Transfer", True),
        ("Remote Execution System Transfer", False),
        ("Resource Exchange Standard Transfer", False),
        ("Rapid Execution Service Transfer", False),
    ]),
    ("What is GraphQL?", [
        ("Query language for APIs", True),
        ("Database", False),
        ("Web framework", False),
        ("Testing tool", False),
    ]),
    ("What is JWT?", [
        ("JSON Web Token", True),
        ("Java Web Tool", False),
        ("JavaScript Web Token", False),
        ("JSON Web Transfer", False),
    ]),
    ("What is OAuth?", [
        ("Authorization framework", True),
        ("Authentication", False),
        ("Encryption", False),
        ("Web protocol", False),
    ]),
    ("What is CORS?", [
        ("Cross-Origin Resource Sharing", True),
        ("Cross-Origin Request Security", False),
        ("Code Origin Resource Sharing", False),
        ("Client Origin Resource Sharing", False),
    ]),
    ("What is MVC?", [
        ("Model-View-Controller", True),
        ("Model-View-Component", False),
        ("Main-View-Controller", False),
        ("Module-View-Controller", False),
    ]),
    ("What is ORM?", [
        ("Object-Relational Mapping", True),
        ("Object Resource Management", False),
        ("Online Resource Manager", False),
        ("Object Reference Model", False),
    ]),
    ("What is TDD?", [
        ("Test-Driven Development", True),
        ("Test Data Development", False),
        ("Type-Driven Development", False),
        ("Tool-Driven Development", False),
    ]),
    ("What is BDD?", [
        ("Behavior-Driven Development", True),
        ("Binary Data Development", False),
        ("Build-Driven Development", False),
        ("Branch-Driven Development", False),
    ]),
    ("What is Agile?", [
        ("Software development methodology", True),
        ("Programming language", False),
        ("Framework", False),
        ("Tool", False),
    ]),
    ("What is Scrum?", [
        ("Agile framework", True),
        ("Programming language", False),
        ("Database", False),
        ("Web server", False),
    ]),
    ("What is Kanban?", [
        ("Visual task management", True),
        ("Code editor", False),
        ("Version control", False),
        ("Project management", False),
    ]),
    ("What is DevOps?", [
        ("Culture and practices", True),
        ("Development tool", False),
        ("Operations system", False),
        ("Deployment script", False),
    ]),
    ("What is cloud computing?", [
        ("On-demand computing resources", True),
        ("Local servers", False),
        ("Personal computers", False),
        ("Mobile devices", False),
    ]),
    ("What is AWS?", [
        ("Amazon Web Services", True),
        ("Advanced Web Server", False),
        ("Automated Web System", False),
        ("Application Web Service", False),
    ]),
    ("What is Azure?", [
        ("Microsoft cloud platform", True),
        ("Database", False),
        ("Web framework", False),
        ("IDE", False),
    ]),
    ("What is GCP?", [
        ("Google Cloud Platform", True),
        ("Global Code Platform", False),
        ("General Computing Platform", False),
        ("Graphics Computing Platform", False),
    ]),
    ("What is serverless?", [
        ("Computing without servers", True),
        ("No servers", False),
        ("Local computing", False),
        ("Peer-to-peer", False),
    ]),
    ("What is microservices?", [
        ("Architectural style", True),
        ("Small services", False),
        ("Web services", False),
        ("API services", False),
    ]),
    ("What is monolithic?", [
        ("Single-tiered software", True),
        ("Multi-tiered", False),
        ("Distributed", False),
        ("Cloud-based", False),
    ]),
    ("What is scalability?", [
        ("Ability to handle growth", True),
        ("Code size", False),
        ("Performance", False),
        ("Security", False),
    ]),
    ("What is load balancing?", [
        ("Distributing load", True),
        ("Balancing code", False),
        ("Server management", False),
        ("Traffic control", False),
    ]),
    ("What is caching?", [
        ("Storing data for quick access", True),
        ("Deleting data", False),
        ("Compressing data", False),
        ("Encrypting data", False),
    ]),
    ("What is CDN?", [
        ("Content Delivery Network", True),
        ("Code Distribution Network", False),
        ("Central Data Node", False),
        ("Cloud Delivery Node", False),
    ]),
    ("What is encryption?", [
        ("Securing data", True),
        ("Compressing data", False),
        ("Storing data", False),
        ("Transmitting data", False),
    ]),
    ("What is hashing?", [
        ("One-way encryption", True),
        ("Two-way encryption", False),
        ("Data compression", False),
        ("Data transmission", False),
    ]),
    ("What is SSL?", [
        ("Secure Sockets Layer", True),
        ("Simple Socket Layer", False),
        ("Secure Server Layer", False),
        ("Standard Security Layer", False),
    ]),
    ("What is TLS?", [
        ("Transport Layer Security", True),
        ("Transport Link Security", False),
        ("Transmission Layer Security", False),
        ("Transfer Layer Security", False),
    ]),
    ("What is firewall?", [
        ("Network security device", True),
        ("Web server", False),
        ("Database", False),
        ("Load balancer", False),
    ]),
    ("What is VPN?", [
        ("Virtual Private Network", True),
        ("Virtual Public Network", False),
        ("Visible Private Network", False),
        ("Virtual Proxy Network", False),
    ]),
    ("What is IP address?", [
        ("Internet Protocol address", True),
        ("Internet Provider address", False),
        ("Internal Protocol address", False),
        ("Identity Provider address", False),
    ]),
    ("What is DNS?", [
        ("Domain Name System", True),
        ("Dynamic Name Server", False),
        ("Domain Network System", False),
        ("Data Name Service", False),
    ]),
    ("What is HTTP?", [
        ("HyperText Transfer Protocol", True),
        ("HyperText Processing Tool", False),
        ("High Transfer Protocol", False),
        ("Hyper Transfer Protocol", False),
    ]),
    ("What is HTTPS?", [
        ("HTTP Secure", True),
        ("HTTP Server", False),
        ("High Security Transfer", False),
        ("Hyper Secure Transfer", False),
    ]),
    ("What is TCP?", [
        ("Transmission Control Protocol", True),
        ("Transfer Control Protocol", False),
        ("Transport Control Protocol", False),
        ("Transmission Communication Protocol", False),
    ]),
    ("What is UDP?", [
        ("User Datagram Protocol", True),
        ("Universal Data Protocol", False),
        ("User Data Protocol", False),
        ("Unified Datagram Protocol", False),
    ]),
    ("What is FTP?", [
        ("File Transfer Protocol", True),
        ("Fast Transfer Protocol", False),
        ("File Transmission Protocol", False),
        ("Full Transfer Protocol", False),
    ]),
    ("What is SSH?", [
        ("Secure Shell", True),
        ("Secure Server Host", False),
        ("Simple Shell Host", False),
        ("Secure System Host", False),
    ]),
    ("What is API key?", [
        ("Access token", True),
        ("Encryption key", False),
        ("Database key", False),
        ("Session key", False),
    ]),
    ("What is webhook?", [
        ("HTTP callback", True),
        ("Web hook", False),
        ("API endpoint", False),
        ("Event listener", False),
    ]),
    ("What is middleware?", [
        ("Software layer", True),
        ("Hardware", False),
        ("Database", False),
        ("Network", False),
    ]),
    ("What is session?", [
        ("User interaction period", True),
        ("Database connection", False),
        ("Server process", False),
        ("API call", False),
    ]),
    ("What is cookie?", [
        ("Small data stored in browser", True),
        ("Web page", False),
        ("Server file", False),
        ("Database record", False),
    ]),
    ("What is localStorage?", [
        ("Browser storage", True),
        ("Server storage", False),
        ("Database", False),
        ("Cache", False),
    ]),
    ("What is sessionStorage?", [
        ("Browser session storage", True),
        ("Server session", False),
        ("Database session", False),
        ("API session", False),
    ]),
    ("What is WebSocket?", [
        ("Full-duplex communication", True),
        ("HTTP protocol", False),
        ("Database connection", False),
        ("File transfer", False),
    ]),
    ("What is AJAX?", [
        ("Asynchronous JavaScript and XML", True),
        ("Advanced JavaScript and XML", False),
        ("Asynchronous JSON and XML", False),
        ("Auto JavaScript and XML", False),
    ]),
    ("What is SPA?", [
        ("Single Page Application", True),
        ("Simple Page App", False),
        ("Single Protocol App", False),
        ("Server Page Application", False),
    ]),
    ("What is PWA?", [
        ("Progressive Web App", True),
        ("Python Web App", False),
        ("Portable Web App", False),
        ("Personal Web App", False),
    ]),
    ("What is React?", [
        ("JavaScript library", True),
        ("Python framework", False),
        ("Database", False),
        ("Web server", False),
    ]),
    ("What is Angular?", [
        ("JavaScript framework", True),
        ("Python library", False),
        ("Web server", False),
        ("Database", False),
    ]),
    ("What is Vue.js?", [
        ("JavaScript framework", True),
        ("Python tool", False),
        ("Web server", False),
        ("Database", False),
    ]),
    ("What is Node.js?", [
        ("JavaScript runtime", True),
        ("Python runtime", False),
        ("Web server", False),
        ("Database", False),
    ]),
    ("What is Express.js?", [
        ("Node.js framework", True),
        ("Python framework", False),
        ("Web server", False),
        ("Database", False),
    ]),
    ("What is Next.js?", [
        ("React framework", True),
        ("Node.js tool", False),
        ("Web server", False),
        ("Database", False),
    ]),
    ("What is Nuxt.js?", [
        ("Vue.js framework", True),
        ("React tool", False),
        ("Web server", False),
        ("Database", False),
    ]),
    ("What is Svelte?", [
        ("JavaScript framework", True),
        ("Python library", False),
        ("Web server", False),
        ("Database", False),
    ]),
    ("What is TypeScript?", [
        ("Typed JavaScript", True),
        ("Python type", False),
        ("Web server", False),
        ("Database", False),
    ]),
    ("What is Babel?", [
        ("JavaScript compiler", True),
        ("Python compiler", False),
        ("Web server", False),
        ("Database", False),
    ]),
    ("What is Webpack?", [
        ("Module bundler", True),
        ("Web server", False),
        ("Database", False),
        ("API tool", False),
    ]),
    ("What is Vite?", [
        ("Build tool", True),
        ("Web server", False),
        ("Database", False),
        ("API tool", False),
    ]),
    ("What is ESLint?", [
        ("JavaScript linter", True),
        ("Python linter", False),
        ("Web server", False),
        ("Database", False),
    ]),
    ("What is Prettier?", [
        ("Code formatter", True),
        ("Web server", False),
        ("Database", False),
        ("API tool", False),
    ]),
    ("What is Jest?", [
        ("JavaScript testing", True),
        ("Python testing", False),
        ("Web server", False),
        ("Database", False),
    ]),
    ("What is Cypress?", [
        ("E2E testing", True),
        ("Unit testing", False),
        ("Web server", False),
        ("Database", False),
    ]),
    ("What is Playwright?", [
        ("Browser automation", True),
        ("Web server", False),
        ("Database", False),
        ("API tool", False),
    ]),
    ("What is Storybook?", [
        ("UI component explorer", True),
        ("Web server", False),
        ("Database", False),
        ("API tool", False),
    ]),
    ("What is Figma?", [
        ("Design tool", True),
        ("Web server", False),
        ("Database", False),
        ("API tool", False),
    ]),
    ("What is Adobe XD?", [
        ("Design tool", True),
        ("Web server", False),
        ("Database", False),
        ("API tool", False),
    ]),
    ("What is Sketch?", [
        ("Design tool", True),
        ("Web server", False),
        ("Database", False),
        ("API tool", False),
    ]),
    ("What is InVision?", [
        ("Prototyping tool", True),
        ("Web server", False),
        ("Database", False),
        ("API tool", False),
    ]),
    ("What is Zeplin?", [
        ("Design handoff", True),
        ("Web server", False),
        ("Database", False),
        ("API tool", False),
    ]),
    ("What is Jira?", [
        ("Project management", True),
        ("Web server", False),
        ("Database", False),
        ("API tool", False),
    ]),
    ("What is Trello?", [
        ("Task management", True),
        ("Web server", False),
        ("Database", False),
        ("API tool", False),
    ]),
    ("What is Slack?", [
        ("Communication tool", True),
        ("Web server", False),
        ("Database", False),
        ("API tool", False),
    ]),
    ("What is Discord?", [
        ("Communication platform", True),
        ("Web server", False),
        ("Database", False),
        ("API tool", False),
    ]),
    ("What is Zoom?", [
        ("Video conferencing", True),
        ("Web server", False),
        ("Database", False),
        ("API tool", False),
    ]),
    ("What is Microsoft Teams?", [
        ("Collaboration tool", True),
        ("Web server", False),
        ("Database", False),
        ("API tool", False),
    ]),
    ("What is Google Meet?", [
        ("Video conferencing", True),
        ("Web server", False),
        ("Database", False),
        ("API tool", False),
    ]),
    ("What is Notion?", [
        ("Note-taking app", True),
        ("Web server", False),
        ("Database", False),
        ("API tool", False),
    ]),
    ("What is Evernote?", [
        ("Note-taking app", True),
        ("Web server", False),
        ("Database", False),
        ("API tool", False),
    ]),
    ("What is Obsidian?", [
        ("Knowledge management", True),
        ("Web server", False),
        ("Database", False),
        ("API tool", False),
    ]),
    ("What is Roam Research?", [
        ("Note-taking tool", True),
        ("Web server", False),
        ("Database", False),
        ("API tool", False),
    ]),
    ("What is Logseq?", [
        ("Knowledge management", True),
        ("Web server", False),
        ("Database", False),
        ("API tool", False),
    ]),
    ("What is VS Code?", [
        ("Code editor", True),
        ("Web server", False),
        ("Database", False),
        ("API tool", False),
    ]),
    ("What is PyCharm?", [
        ("Python IDE", True),
        ("Web server", False),
        ("Database", False),
        ("API tool", False),
    ]),
    ("What is Jupyter?", [
        ("Interactive computing", True),
        ("Web server", False),
        ("Database", False),
        ("API tool", False),
    ]),
    ("What is Anaconda?", [
        ("Python distribution", True),
        ("Web server", False),
        ("Database", False),
        ("API tool", False),
    ]),
    ("What is Conda?", [
        ("Package manager", True),
        ("Web server", False),
        ("Database", False),
        ("API tool", False),
    ]),
    ("What is Poetry?", [
        ("Python dependency management", True),
        ("Web server", False),
        ("Database", False),
        ("API tool", False),
    ]),
    ("What is Pipenv?", [
        ("Python virtual environments", True),
        ("Web server", False),
        ("Database", False),
        ("API tool", False),
    ]),
    ("What is Black?", [
        ("Python code formatter", True),
        ("Web server", False),
        ("Database", False),
        ("API tool", False),
    ]),
    ("What is Flake8?", [
        ("Python linter", True),
        ("Web server", False),
        ("Database", False),
        ("API tool", False),
    ]),
    ("What is MyPy?", [
        ("Static type checker", True),
        ("Web server", False),
        ("Database", False),
        ("API tool", False),
    ]),
    ("What is Pylint?", [
        ("Python linter", True),
        ("Web server", False),
        ("Database", False),
        ("API tool", False),
    ]),
    ("What is Bandit?", [
        ("Security linter", True),
        ("Web server", False),
        ("Database", False),
        ("API tool", False),
    ]),
    ("What is Coverage.py?", [
        ("Code coverage tool", True),
        ("Web server", False),
        ("Database", False),
        ("API tool", False),
    ]),
    ("What is Tox?", [
        ("Testing automation", True),
        ("Web server", False),
        ("Database", False),
        ("API tool", False),
    ]),
    ("What is Sphinx?", [
        ("Documentation generator", True),
        ("Web server", False),
        ("Database", False),
        ("API tool", False),
    ]),
    ("What is MkDocs?", [
        ("Static site generator", True),
        ("Web server", False),
        ("Database", False),
        ("API tool", False),
    ]),
    ("What is Read the Docs?", [
        ("Documentation hosting", True),
        ("Web server", False),
        ("Database", False),
        ("API tool", False),
    ]),
    ("What is GitLab?", [
        ("DevOps platform", True),
        ("Web server", False),
        ("Database", False),
        ("API tool", False),
    ]),
    ("What is Bitbucket?", [
        ("Git repository hosting", True),
        ("Web server", False),
        ("Database", False),
        ("API tool", False),
    ]),
    ("What is Heroku?", [
        ("Cloud platform", True),
        ("Web server", False),
        ("Database", False),
        ("API tool", False),
    ]),
]


class Command(BaseCommand):
    help = 'Seed 100 Python-related questions into the quiz app (idempotent)'

    def handle(self, *args, **options):
        created = 0
        python_subj, _ = Subject.objects.get_or_create(name='Python')
        # Remove existing Python questions
        Question.objects.filter(subject=python_subj).delete()
        for q_text, choices in QUESTIONS:
            q = Question.objects.create(text=q_text, subject=python_subj)
            created += 1
            # create choices
            for choice_text, is_correct in choices:
                Choice.objects.create(question=q, text=choice_text, is_correct=is_correct)
        self.stdout.write(self.style.SUCCESS(f'Successfully seeded {created} Python questions.'))
