from django.core.management.base import BaseCommand
from quiz.models import Question, Choice, Subject

QUESTIONS = [
    ("What is the derivative of sin(x)?", [
        ("cos(x)", True),
        ("-cos(x)", False),
        ("sin(x)", False),
        ("tan(x)", False),
    ]),
    ("What is the value of ∫x dx?", [
        ("x²/2 + C", True),
        ("x² + C", False),
        ("x + C", False),
        ("2x + C", False),
    ]),
    ("Which law states that force equals mass times acceleration?", [
        ("Newton's second law", True),
        ("Newton's first law", False),
        ("Newton's third law", False),
        ("Law of gravitation", False),
    ]),
    ("What is the speed of light in vacuum?", [
        ("3 × 10^8 m/s", True),
        ("3 × 10^6 m/s", False),
        ("3 × 10^10 m/s", False),
        ("3 × 10^4 m/s", False),
    ]),
    ("What is the chemical formula for water?", [
        ("H2O", True),
        ("HO", False),
        ("H2O2", False),
        ("OH2", False),
    ]),
    ("What is the limit of (sin(x))/x as x approaches 0?", [
        ("1", True),
        ("0", False),
        ("∞", False),
        ("-1", False),
    ]),
    ("Which particle has a positive charge?", [
        ("Proton", True),
        ("Electron", False),
        ("Neutron", False),
        ("Photon", False),
    ]),
    ("What is the area of a circle with radius r?", [
        ("πr²", True),
        ("2πr", False),
        ("πr", False),
        ("r²", False),
    ]),
    ("What is the unit of electric charge?", [
        ("Coulomb", True),
        ("Volt", False),
        ("Ampere", False),
        ("Ohm", False),
    ]),
    ("What is the pH of a neutral solution?", [
        ("7", True),
        ("0", False),
        ("14", False),
        ("1", False),
    ]),
    ("What is the integral of e^x dx?", [
        ("e^x + C", True),
        ("e^x", False),
        ("x e^x + C", False),
        ("ln(e^x) + C", False),
    ]),
    ("Which force acts between two charged particles?", [
        ("Electrostatic force", True),
        ("Gravitational force", False),
        ("Magnetic force", False),
        ("Frictional force", False),
    ]),
    ("What is the atomic number of carbon?", [
        ("6", True),
        ("8", False),
        ("12", False),
        ("14", False),
    ]),
    ("What is the derivative of ln(x)?", [
        ("1/x", True),
        ("x", False),
        ("ln(x)", False),
        ("e^x", False),
    ]),
    ("What is the SI unit of energy?", [
        ("Joule", True),
        ("Watt", False),
        ("Newton", False),
        ("Pascal", False),
    ]),
    ("What is the chemical symbol for sodium?", [
        ("Na", True),
        ("So", False),
        ("Sd", False),
        ("Nm", False),
    ]),
    ("What is the value of √(4)?", [
        ("2", True),
        ("4", False),
        ("8", False),
        ("16", False),
    ]),
    ("Which law states that every action has an equal and opposite reaction?", [
        ("Newton's third law", True),
        ("Newton's first law", False),
        ("Newton's second law", False),
        ("Law of conservation of energy", False),
    ]),
    ("What is the boiling point of water at standard pressure?", [
        ("100°C", True),
        ("0°C", False),
        ("50°C", False),
        ("200°C", False),
    ]),
    ("What is the derivative of x^n?", [
        ("n x^(n-1)", True),
        ("x^n", False),
        ("n x^n", False),
        ("x^(n-1)", False),
    ]),
    ("What is the unit of magnetic field?", [
        ("Tesla", True),
        ("Gauss", False),
        ("Weber", False),
        ("Henry", False),
    ]),
    ("What is the chemical formula for methane?", [
        ("CH4", True),
        ("C2H6", False),
        ("C3H8", False),
        ("C4H10", False),
    ]),
    ("What is the limit of (1 - cos(x))/x as x approaches 0?", [
        ("0", True),
        ("1", False),
        ("∞", False),
        ("-1", False),
    ]),
    ("Which particle is responsible for mediating strong nuclear force?", [
        ("Gluon", True),
        ("Photon", False),
        ("W boson", False),
        ("Z boson", False),
    ]),
    ("What is the area under the curve y = x from 0 to 1?", [
        ("1/2", True),
        ("1", False),
        ("2", False),
        ("0", False),
    ]),
    ("What is the unit of pressure?", [
        ("Pascal", True),
        ("Newton", False),
        ("Joule", False),
        ("Watt", False),
    ]),
    ("What is the chemical symbol for potassium?", [
        ("K", True),
        ("P", False),
        ("Po", False),
        ("Pt", False),
    ]),
    ("What is the derivative of cos(x)?", [
        ("-sin(x)", True),
        ("sin(x)", False),
        ("cos(x)", False),
        ("tan(x)", False),
    ]),
    ("What is the speed of sound in air?", [
        ("343 m/s", True),
        ("300 m/s", False),
        ("400 m/s", False),
        ("500 m/s", False),
    ]),
    ("What is the atomic mass of hydrogen?", [
        ("1 u", True),
        ("2 u", False),
        ("4 u", False),
        ("16 u", False),
    ]),
    ("What is the integral of 1/x dx?", [
        ("ln|x| + C", True),
        ("x + C", False),
        ("1/x + C", False),
        ("x²/2 + C", False),
    ]),
    ("Which law states that the total energy of an isolated system remains constant?", [
        ("Law of conservation of energy", True),
        ("First law of thermodynamics", False),
        ("Second law of thermodynamics", False),
        ("Zeroth law of thermodynamics", False),
    ]),
    ("What is the freezing point of water?", [
        ("0°C", True),
        ("100°C", False),
        ("-273°C", False),
        ("50°C", False),
    ]),
    ("What is the derivative of tan(x)?", [
        ("sec²(x)", True),
        ("cos²(x)", False),
        ("sin²(x)", False),
        ("tan²(x)", False),
    ]),
    ("What is the unit of capacitance?", [
        ("Farad", True),
        ("Henry", False),
        ("Tesla", False),
        ("Siemens", False),
    ]),
    ("What is the chemical formula for carbon dioxide?", [
        ("CO2", True),
        ("CO", False),
        ("C2O", False),
        ("C2O2", False),
    ]),
    ("What is the value of sin(90°)?", [
        ("1", True),
        ("0", False),
        ("-1", False),
        ("√2/2", False),
    ]),
    ("Which force is responsible for holding the nucleus together?", [
        ("Strong nuclear force", True),
        ("Weak nuclear force", False),
        ("Electromagnetic force", False),
        ("Gravitational force", False),
    ]),
    ("What is the volume of a sphere with radius r?", [
        ("(4/3)πr³", True),
        ("(4/3)πr²", False),
        ("πr³", False),
        ("2πr³", False),
    ]),
    ("What is the unit of inductance?", [
        ("Henry", True),
        ("Farad", False),
        ("Tesla", False),
        ("Siemens", False),
    ]),
    ("What is the chemical symbol for calcium?", [
        ("Ca", True),
        ("C", False),
        ("Cl", False),
        ("Cu", False),
    ]),
    ("What is the derivative of e^x?", [
        ("e^x", True),
        ("x e^x", False),
        ("ln(x)", False),
        ("1/x", False),
    ]),
    ("What is the wavelength of visible light?", [
        ("400-700 nm", True),
        ("100-400 nm", False),
        ("700-1000 nm", False),
        ("1-10 nm", False),
    ]),
    ("What is the atomic number of oxygen?", [
        ("8", True),
        ("6", False),
        ("10", False),
        ("12", False),
    ]),
    ("What is the integral of sin(x) dx?", [
        ("-cos(x) + C", True),
        ("cos(x) + C", False),
        ("sin(x) + C", False),
        ("tan(x) + C", False),
    ]),
    ("Which law states that the pressure of a gas is inversely proportional to its volume?", [
        ("Boyle's law", True),
        ("Charles's law", False),
        ("Gay-Lussac's law", False),
        ("Avogadro's law", False),
    ]),
    ("What is the density of water?", [
        ("1000 kg/m³", True),
        ("100 kg/m³", False),
        ("10 kg/m³", False),
        ("10000 kg/m³", False),
    ]),
    ("What is the derivative of sec(x)?", [
        ("sec(x) tan(x)", True),
        ("cos(x)", False),
        ("sin(x)", False),
        ("tan(x)", False),
    ]),
    ("What is the unit of resistance?", [
        ("Ohm", True),
        ("Volt", False),
        ("Ampere", False),
        ("Watt", False),
    ]),
    ("What is the chemical formula for sulfuric acid?", [
        ("H2SO4", True),
        ("HCl", False),
        ("HNO3", False),
        ("H3PO4", False),
    ]),
    ("What is the value of cos(0°)?", [
        ("1", True),
        ("0", False),
        ("-1", False),
        ("√2/2", False),
    ]),
    ("Which particle has no charge?", [
        ("Neutron", True),
        ("Proton", False),
        ("Electron", False),
        ("Positron", False),
    ]),
    ("What is the surface area of a sphere with radius r?", [
        ("4πr²", True),
        ("2πr²", False),
        ("πr²", False),
        ("4πr³", False),
    ]),
    ("What is the unit of conductance?", [
        ("Siemens", True),
        ("Ohm", False),
        ("Volt", False),
        ("Ampere", False),
    ]),
    ("What is the chemical symbol for magnesium?", [
        ("Mg", True),
        ("Mn", False),
        ("Mo", False),
        ("Ma", False),
    ]),
    ("What is the derivative of ln(x)?", [
        ("1/x", True),
        ("x", False),
        ("ln(x)", False),
        ("e^x", False),
    ]),
    ("What is the Planck's constant?", [
        ("6.626 × 10^-34 J s", True),
        ("1.602 × 10^-19 C", False),
        ("9.109 × 10^-31 kg", False),
        ("1.381 × 10^-23 J/K", False),
    ]),
    ("What is the atomic number of nitrogen?", [
        ("7", True),
        ("6", False),
        ("8", False),
        ("9", False),
    ]),
    ("What is the integral of cos(x) dx?", [
        ("sin(x) + C", True),
        ("-sin(x) + C", False),
        ("cos(x) + C", False),
        ("tan(x) + C", False),
    ]),
    ("Which law states that the volume of a gas is directly proportional to its temperature?", [
        ("Charles's law", True),
        ("Boyle's law", False),
        ("Gay-Lussac's law", False),
        ("Avogadro's law", False),
    ]),
    ("What is the molar mass of water?", [
        ("18 g/mol", True),
        ("16 g/mol", False),
        ("20 g/mol", False),
        ("14 g/mol", False),
    ]),
    ("What is the derivative of csc(x)?", [
        ("-csc(x) cot(x)", True),
        ("sec(x)", False),
        ("cos(x)", False),
        ("sin(x)", False),
    ]),
    ("What is the unit of electric field?", [
        ("Volt per meter", True),
        ("Tesla", False),
        ("Henry", False),
        ("Farad", False),
    ]),
    ("What is the chemical formula for ammonia?", [
        ("NH3", True),
        ("N2H4", False),
        ("NH4OH", False),
        ("N2O", False),
    ]),
    ("What is the value of tan(45°)?", [
        ("1", True),
        ("0", False),
        ("√3", False),
        ("∞", False),
    ]),
    ("Which force is responsible for radioactive decay?", [
        ("Weak nuclear force", True),
        ("Strong nuclear force", False),
        ("Electromagnetic force", False),
        ("Gravitational force", False),
    ]),
    ("What is the perimeter of a circle with radius r?", [
        ("2πr", True),
        ("πr", False),
        ("πr²", False),
        ("2πr²", False),
    ]),
    ("What is the unit of magnetic flux?", [
        ("Weber", True),
        ("Tesla", False),
        ("Henry", False),
        ("Farad", False),
    ]),
    ("What is the chemical symbol for aluminum?", [
        ("Al", True),
        ("A", False),
        ("Alu", False),
        ("Alm", False),
    ]),
    ("What is the derivative of x^2?", [
        ("2x", True),
        ("x", False),
        ("2x²", False),
        ("x²", False),
    ]),
    ("What is the Avogadro's number?", [
        ("6.022 × 10^23", True),
        ("3.1416", False),
        ("1.602 × 10^-19", False),
        ("9.8", False),
    ]),
    ("What is the atomic number of hydrogen?", [
        ("1", True),
        ("2", False),
        ("3", False),
        ("4", False),
    ]),
    ("What is the integral of sec²(x) dx?", [
        ("tan(x) + C", True),
        ("sec(x) + C", False),
        ("cot(x) + C", False),
        ("csc(x) + C", False),
    ]),
    ("Which law states that the rate of effusion of a gas is inversely proportional to the square root of its molecular mass?", [
        ("Graham's law", True),
        ("Boyle's law", False),
        ("Charles's law", False),
        ("Dalton's law", False),
    ]),
    ("What is the specific heat of water?", [
        ("4186 J/kg°C", True),
        ("1000 J/kg°C", False),
        ("2000 J/kg°C", False),
        ("500 J/kg°C", False),
    ]),
    ("What is the derivative of cot(x)?", [
        ("-csc²(x)", True),
        ("sec²(x)", False),
        ("cos²(x)", False),
        ("sin²(x)", False),
    ]),
    ("What is the unit of electric potential?", [
        ("Volt", True),
        ("Ampere", False),
        ("Ohm", False),
        ("Watt", False),
    ]),
    ("What is the chemical formula for nitric acid?", [
        ("HNO3", True),
        ("HCl", False),
        ("H2SO4", False),
        ("H3PO4", False),
    ]),
    ("What is the value of sin(30°)?", [
        ("1/2", True),
        ("1", False),
        ("√3/2", False),
        ("0", False),
    ]),
    ("Which particle is responsible for mediating electromagnetic force?", [
        ("Photon", True),
        ("Gluon", False),
        ("W boson", False),
        ("Z boson", False),
    ]),
    ("What is the diagonal of a square with side a?", [
        ("a√2", True),
        ("a", False),
        ("2a", False),
        ("a²", False),
    ]),
    ("What is the unit of luminous intensity?", [
        ("Candela", True),
        ("Lumen", False),
        ("Lux", False),
        ("Watt", False),
    ]),
    ("What is the chemical symbol for zinc?", [
        ("Zn", True),
        ("Z", False),
        ("Zi", False),
        ("Ze", False),
    ]),
    ("What is the derivative of x^3?", [
        ("3x²", True),
        ("x²", False),
        ("3x³", False),
        ("x³", False),
    ]),
    ("What is the Boltzmann constant?", [
        ("1.381 × 10^-23 J/K", True),
        ("6.626 × 10^-34 J s", False),
        ("1.602 × 10^-19 C", False),
        ("9.109 × 10^-31 kg", False),
    ]),
    ("What is the atomic number of helium?", [
        ("2", True),
        ("1", False),
        ("3", False),
        ("4", False),
    ]),
    ("What is the integral of tan(x) dx?", [
        ("-ln|cos(x)| + C", True),
        ("ln|sin(x)| + C", False),
        ("sec(x) + C", False),
        ("csc(x) + C", False),
    ]),
    ("Which law states that the total pressure of a mixture of gases is the sum of the partial pressures?", [
        ("Dalton's law", True),
        ("Boyle's law", False),
        ("Charles's law", False),
        ("Avogadro's law", False),
    ]),
    ("What is the latent heat of vaporization of water?", [
        ("2260 kJ/kg", True),
        ("334 kJ/kg", False),
        ("4186 kJ/kg", False),
        ("1000 kJ/kg", False),
    ]),
    ("What is the derivative of sec(x)?", [
        ("sec(x) tan(x)", True),
        ("cos(x)", False),
        ("sin(x)", False),
        ("tan(x)", False),
    ]),
    ("What is the unit of frequency?", [
        ("Hertz", True),
        ("Watt", False),
        ("Volt", False),
        ("Ampere", False),
    ]),
    ("What is the chemical formula for hydrochloric acid?", [
        ("HCl", True),
        ("H2SO4", False),
        ("HNO3", False),
        ("H3PO4", False),
    ]),
    ("What is the value of cos(60°)?", [
        ("1/2", True),
        ("1", False),
        ("0", False),
        ("√3/2", False),
    ]),
    ("Which particle is responsible for mediating gravitational force?", [
        ("Graviton", True),
        ("Photon", False),
        ("Gluon", False),
        ("W boson", False),
    ]),
    ("What is the area of an equilateral triangle with side a?", [
        ("(√3/4) a²", True),
        ("a²", False),
        ("(1/2) a²", False),
        ("(3/4) a²", False),
    ]),
    ("What is the unit of luminous flux?", [
        ("Lumen", True),
        ("Candela", False),
        ("Lux", False),
        ("Watt", False),
    ]),
    ("What is the chemical symbol for iron?", [
        ("Fe", True),
        ("I", False),
        ("Ir", False),
        ("In", False),
    ]),
    ("What is the derivative of x^4?", [
        ("4x³", True),
        ("x³", False),
        ("4x⁴", False),
        ("x⁴", False),
    ]),
    ("What is the Rydberg constant?", [
        ("1.097 × 10^7 m^-1", True),
        ("6.626 × 10^-34 J s", False),
        ("1.602 × 10^-19 C", False),
        ("9.109 × 10^-31 kg", False),
    ]),
    ("What is the atomic number of lithium?", [
        ("3", True),
        ("1", False),
        ("2", False),
        ("4", False),
    ]),
    ("What is the integral of csc²(x) dx?", [
        ("-cot(x) + C", True),
        ("cot(x) + C", False),
        ("tan(x) + C", False),
        ("sec(x) + C", False),
    ]),
    ("Which law states that equal volumes of gases contain equal number of molecules?", [
        ("Avogadro's law", True),
        ("Boyle's law", False),
        ("Charles's law", False),
        ("Gay-Lussac's law", False),
    ]),
    ("What is the latent heat of fusion of water?", [
        ("334 kJ/kg", True),
        ("2260 kJ/kg", False),
        ("4186 kJ/kg", False),
        ("1000 kJ/kg", False),
    ]),
    ("What is the derivative of csc(x)?", [
        ("-csc(x) cot(x)", True),
        ("sec(x)", False),
        ("cos(x)", False),
        ("sin(x)", False),
    ]),
    ("What is the unit of illuminance?", [
        ("Lux", True),
        ("Lumen", False),
        ("Candela", False),
        ("Watt", False),
    ]),
    ("What is the chemical formula for phosphoric acid?", [
        ("H3PO4", True),
        ("HCl", False),
        ("H2SO4", False),
        ("HNO3", False),
    ]),
    ("What is the value of sin(45°)?", [
        ("√2/2", True),
        ("1", False),
        ("1/2", False),
        ("0", False),
    ]),
    ("Which particle has a mass of 0?", [
        ("Photon", True),
        ("Electron", False),
        ("Proton", False),
        ("Neutron", False),
    ]),
    ("What is the circumference of a circle with radius r?", [
        ("2πr", True),
        ("πr", False),
        ("πr²", False),
        ("2πr²", False),
    ]),
    ("What is the unit of electric dipole moment?", [
        ("Coulomb meter", True),
        ("Tesla", False),
        ("Henry", False),
        ("Farad", False),
    ]),
    ("What is the chemical symbol for copper?", [
        ("Cu", True),
        ("C", False),
        ("Co", False),
        ("Cp", False),
    ]),
    ("What is the derivative of x^5?", [
        ("5x⁴", True),
        ("x⁴", False),
        ("5x⁵", False),
        ("x⁵", False),
    ]),
    ("What is the Stefan-Boltzmann constant?", [
        ("5.67 × 10^-8 W/m²K⁴", True),
        ("6.626 × 10^-34 J s", False),
        ("1.602 × 10^-19 C", False),
        ("9.109 × 10^-31 kg", False),
    ]),
    ("What is the atomic number of beryllium?", [
        ("4", True),
        ("2", False),
        ("3", False),
        ("5", False),
    ]),
    ("What is the integral of sec(x) tan(x) dx?", [
        ("sec(x) + C", True),
        ("tan(x) + C", False),
        ("csc(x) + C", False),
        ("cot(x) + C", False),
    ]),
    ("Which law states that the pressure of a gas is directly proportional to its temperature?", [
        ("Gay-Lussac's law", True),
        ("Boyle's law", False),
        ("Charles's law", False),
        ("Avogadro's law", False),
    ]),
    ("What is the universal gas constant?", [
        ("8.314 J/mol K", True),
        ("1.381 × 10^-23 J/K", False),
        ("6.022 × 10^23", False),
        ("9.8 m/s²", False),
    ]),
    ("What is the derivative of sinh(x)?", [
        ("cosh(x)", True),
        ("sinh(x)", False),
        ("tanh(x)", False),
        ("sech(x)", False),
    ]),
    ("What is the unit of torque?", [
        ("Newton meter", True),
        ("Joule", False),
        ("Watt", False),
        ("Pascal", False),
    ]),
    ("What is the chemical formula for acetic acid?", [
        ("CH3COOH", True),
        ("C2H4O2", False),
        ("C2H6O", False),
        ("C3H6O", False),
    ]),
    ("What is the value of cos(45°)?", [
        ("√2/2", True),
        ("1", False),
        ("0", False),
        ("1/2", False),
    ]),
    ("Which particle is responsible for mediating weak nuclear force?", [
        ("W and Z bosons", True),
        ("Photon", False),
        ("Gluon", False),
        ("Graviton", False),
    ]),
    ("What is the area of a rectangle with length l and width w?", [
        ("l w", True),
        ("l + w", False),
        ("2(l + w)", False),
        ("l² + w²", False),
    ]),
    ("What is the unit of angular momentum?", [
        ("Kilogram meter squared per second", True),
        ("Joule", False),
        ("Watt", False),
        ("Pascal", False),
    ]),
    ("What is the chemical symbol for silver?", [
        ("Ag", True),
        ("A", False),
        ("Au", False),
        ("Al", False),
    ]),
    ("What is the derivative of x^6?", [
        ("6x⁵", True),
        ("x⁵", False),
        ("6x⁶", False),
        ("x⁶", False),
    ]),
    ("What is the Wien's displacement constant?", [
        ("2.897 × 10^-3 m K", True),
        ("6.626 × 10^-34 J s", False),
        ("1.602 × 10^-19 C", False),
        ("9.109 × 10^-31 kg", False),
    ]),
    ("What is the atomic number of boron?", [
        ("5", True),
        ("3", False),
        ("4", False),
        ("6", False),
    ]),
    ("What is the integral of csc(x) cot(x) dx?", [
        ("-csc(x) + C", True),
        ("csc(x) + C", False),
        ("sec(x) + C", False),
        ("cot(x) + C", False),
    ]),
    ("Which law states that the entropy of an isolated system never decreases?", [
        ("Second law of thermodynamics", True),
        ("First law of thermodynamics", False),
        ("Zeroth law of thermodynamics", False),
        ("Third law of thermodynamics", False),
    ]),
    ("What is the acceleration due to gravity on Earth?", [
        ("9.8 m/s²", True),
        ("10 m/s²", False),
        ("9.81 m/s²", False),
        ("8.9 m/s²", False),
    ]),
    ("What is the derivative of cosh(x)?", [
        ("sinh(x)", True),
        ("cosh(x)", False),
        ("tanh(x)", False),
        ("sech(x)", False),
    ]),
    ("What is the unit of impulse?", [
        ("Newton second", True),
        ("Joule", False),
        ("Watt", False),
        ("Pascal", False),
    ]),
    ("What is the chemical formula for ethanol?", [
        ("C2H5OH", True),
        ("C2H6O", False),
        ("C3H8O", False),
        ("C4H10O", False),
    ]),
    ("What is the value of tan(30°)?", [
        ("1/√3", True),
        ("1", False),
        ("√3", False),
        ("0", False),
    ]),
    ("Which particle has a charge of +1?", [
        ("Proton", True),
        ("Electron", False),
        ("Neutron", False),
        ("Positron", False),
    ]),
    ("What is the perimeter of a rectangle with length l and width w?", [
        ("2(l + w)", True),
        ("l w", False),
        ("l + w", False),
        ("l² + w²", False),
    ]),
    ("What is the unit of momentum?", [
        ("Kilogram meter per second", True),
        ("Joule", False),
        ("Watt", False),
        ("Pascal", False),
    ]),
    ("What is the chemical symbol for gold?", [
        ("Au", True),
        ("Ag", False),
        ("Fe", False),
        ("Cu", False),
    ]),
    ("What is the derivative of x^7?", [
        ("7x⁶", True),
        ("x⁶", False),
        ("7x⁷", False),
        ("x⁷", False),
    ]),
    ("What is the Faraday constant?", [
        ("96485 C/mol", True),
        ("6.626 × 10^-34 J s", False),
        ("1.602 × 10^-19 C", False),
        ("9.109 × 10^-31 kg", False),
    ]),
    ("What is the atomic number of carbon?", [
        ("6", True),
        ("8", False),
        ("12", False),
        ("14", False),
    ]),
    ("What is the integral of sinh(x) dx?", [
        ("cosh(x) + C", True),
        ("sinh(x) + C", False),
        ("tanh(x) + C", False),
        ("sech(x) + C", False),
    ]),
    ("Which law states that the entropy of a perfect crystal is zero at absolute zero?", [
        ("Third law of thermodynamics", True),
        ("First law of thermodynamics", False),
        ("Second law of thermodynamics", False),
        ("Zeroth law of thermodynamics", False),
    ]),
    ("What is the speed of sound in water?", [
        ("1500 m/s", True),
        ("343 m/s", False),
        ("300 m/s", False),
        ("500 m/s", False),
    ]),
    ("What is the derivative of tanh(x)?", [
        ("sech²(x)", True),
        ("cosh²(x)", False),
        ("sinh²(x)", False),
        ("tanh²(x)", False),
    ]),
    ("What is the unit of work?", [
        ("Joule", True),
        ("Watt", False),
        ("Volt", False),
        ("Ampere", False),
    ]),
    ("What is the chemical formula for benzene?", [
        ("C6H6", True),
        ("C6H12", False),
        ("C6H14", False),
        ("C6H8", False),
    ]),
    ("What is the value of sin(60°)?", [
        ("√3/2", True),
        ("1", False),
        ("1/2", False),
        ("0", False),
    ]),
    ("Which particle has a charge of -1?", [
        ("Electron", True),
        ("Proton", False),
        ("Neutron", False),
        ("Positron", False),
    ]),
    ("What is the area of a triangle with base b and height h?", [
        ("(1/2) b h", True),
        ("b h", False),
        ("2 b h", False),
        ("b² + h²", False),
    ]),
    ("What is the unit of power?", [
        ("Watt", True),
        ("Joule", False),
        ("Newton", False),
        ("Pascal", False),
    ]),
    ("What is the chemical symbol for mercury?", [
        ("Hg", True),
        ("H", False),
        ("He", False),
        ("Ho", False),
    ]),
    ("What is the derivative of x^8?", [
        ("8x⁷", True),
        ("x⁷", False),
        ("8x⁸", False),
        ("x⁸", False),
    ]),
    ("What is the electron charge?", [
        ("-1.602 × 10^-19 C", True),
        ("6.626 × 10^-34 J s", False),
        ("9.109 × 10^-31 kg", False),
        ("1.381 × 10^-23 J/K", False),
    ]),
    ("What is the atomic number of neon?", [
        ("10", True),
        ("8", False),
        ("9", False),
        ("11", False),
    ]),
    ("What is the integral of cosh(x) dx?", [
        ("sinh(x) + C", True),
        ("cosh(x) + C", False),
        ("tanh(x) + C", False),
        ("sech(x) + C", False),
    ]),
    ("Which law states that two systems in thermal equilibrium with a third are in equilibrium with each other?", [
        ("Zeroth law of thermodynamics", True),
        ("First law of thermodynamics", False),
        ("Second law of thermodynamics", False),
        ("Third law of thermodynamics", False),
    ]),
    ("What is the speed of light in glass?", [
        ("2 × 10^8 m/s", True),
        ("3 × 10^8 m/s", False),
        ("1.5 × 10^8 m/s", False),
        ("2.5 × 10^8 m/s", False),
    ]),
    ("What is the derivative of sech(x)?", [
        ("-sech(x) tanh(x)", True),
        ("cosh(x)", False),
        ("sinh(x)", False),
        ("tanh(x)", False),
    ]),
    ("What is the unit of heat?", [
        ("Joule", True),
        ("Watt", False),
        ("Volt", False),
        ("Ampere", False),
    ]),
    ("What is the chemical formula for urea?", [
        ("CH4N2O", True),
        ("C2H6N2O", False),
        ("C3H8N2O", False),
        ("C4H10N2O", False),
    ]),
    ("What is the value of cos(30°)?", [
        ("√3/2", True),
        ("1", False),
        ("1/2", False),
        ("0", False),
    ]),
    ("Which particle has a mass equal to electron?", [
        ("Positron", True),
        ("Proton", False),
        ("Neutron", False),
        ("Muon", False),
    ]),
    ("What is the volume of a cube with side a?", [
        ("a³", True),
        ("a²", False),
        ("3a", False),
        ("a", False),
    ]),
    ("What is the unit of angular velocity?", [
        ("Radian per second", True),
        ("Joule", False),
        ("Watt", False),
        ("Pascal", False),
    ]),
    ("What is the chemical symbol for lead?", [
        ("Pb", True),
        ("P", False),
        ("Pd", False),
        ("Pt", False),
    ]),
    ("What is the derivative of x^9?", [
        ("9x⁸", True),
        ("x⁸", False),
        ("9x⁹", False),
        ("x⁹", False),
    ]),
    ("What is the proton mass?", [
        ("1.673 × 10^-27 kg", True),
        ("9.109 × 10^-31 kg", False),
        ("1.602 × 10^-19 C", False),
        ("6.626 × 10^-34 J s", False),
    ]),
    ("What is the atomic number of sodium?", [
        ("11", True),
        ("10", False),
        ("12", False),
        ("13", False),
    ]),
    ("What is the integral of tanh(x) dx?", [
        ("ln|cosh(x)| + C", True),
        ("sinh(x) + C", False),
        ("cosh(x) + C", False),
        ("sech(x) + C", False),
    ]),
    ("Which law states that the internal energy of a system is a state function?", [
        ("First law of thermodynamics", True),
        ("Second law of thermodynamics", False),
        ("Zeroth law of thermodynamics", False),
        ("Third law of thermodynamics", False),
    ]),
    ("What is the speed of sound in water?", [
        ("1500 m/s", True),
        ("343 m/s", False),
        ("300 m/s", False),
        ("500 m/s", False),
    ]),
]


class Command(BaseCommand):
    help = 'Seed 100 JEE-related questions into the quiz app (idempotent)'

    def handle(self, *args, **options):
        created = 0
        jee_subj, _ = Subject.objects.get_or_create(name='JEE')
        # Remove existing JEE questions
        Question.objects.filter(subject=jee_subj).delete()
        for q_text, choices in QUESTIONS:
            q = Question.objects.create(text=q_text, subject=jee_subj)
            created += 1
            # create choices
            for choice_text, is_correct in choices:
                Choice.objects.create(question=q, text=choice_text, is_correct=is_correct)
        self.stdout.write(self.style.SUCCESS(f'Successfully seeded {created} JEE questions.'))
