from django.core.management.base import BaseCommand
from quiz.models import Question, Choice, Subject

QUESTIONS = [
    ("What does JavaScript stand for?", [
        ("Java + Script", True),
        ("JavaScript", False),
        ("Java + Style", False),
        ("Java + Server", False),
    ]),
    ("Which company developed JavaScript?", [
        ("Netscape", True),
        ("Microsoft", False),
        ("Google", False),
        ("Apple", False),
    ]),
    ("What is the correct syntax for referring to an external script called 'script.js'?", [
        ("<script src='script.js'>", True),
        ("<script href='script.js'>", False),
        ("<script ref='script.js'>", False),
        ("<script name='script.js'>", False),
    ]),
    ("The external JavaScript file must contain the <script> tag.", [
        ("False", True),
        ("True", False),
        ("Only if it's inline", False),
        ("Always", False),
    ]),
    ("How do you write 'Hello World' in an alert box?", [
        ("alert('Hello World')", True),
        ("msg('Hello World')", False),
        ("msgBox('Hello World')", False),
        ("alertBox('Hello World')", False),
    ]),
    ("How do you create a function in JavaScript?", [
        ("function myFunction()", True),
        ("function: myFunction()", False),
        ("function = myFunction()", False),
        ("myFunction() function", False),
    ]),
    ("How do you call a function named 'myFunction'?", [
        ("myFunction()", True),
        ("call myFunction()", False),
        ("call function myFunction()", False),
        ("run myFunction()", False),
    ]),
    ("How to write an IF statement in JavaScript?", [
        ("if (i == 5)", True),
        ("if i == 5 then", False),
        ("if i = 5 then", False),
        ("if i = 5", False),
    ]),
    ("How can you add a comment in a JavaScript?", [
        ("//This is a comment", True),
        ("<!--This is a comment-->", False),
        ("/*This is a comment*/", False),
        ("#This is a comment", False),
    ]),
    ("How to insert a JavaScript into an HTML page?", [
        ("All of the above", True),
        ("<script>", False),
        ("<script src='myscript.js'>", False),
        ("<javascript>", False),
    ]),
    ("What is the correct JavaScript syntax to insert a comment that has more than one line?", [
        ("/*This comment has\n more than one line*/", True),
        ("//This comment has\n more than one line", False),
        ("<!--This comment has\n more than one line-->", False),
        ("/*This comment has more than one line*/", False),
    ]),
    ("What is the correct syntax for referring to an external script called 'xxx.js'?", [
        ("<script src='xxx.js'>", True),
        ("<script href='xxx.js'>", False),
        ("<script name='xxx.js'>", False),
        ("<script ref='xxx.js'>", False),
    ]),
    ("The external JavaScript file must contain the <script> tag.", [
        ("False", True),
        ("True", False),
        ("Only if it's inline", False),
        ("Always", False),
    ]),
    ("How do you write 'Hello World' in an alert box?", [
        ("alertBox('Hello World')", True),
        ("msgBox('Hello World')", False),
        ("alert('Hello World')", False),
        ("msg('Hello World')", False),
    ]),
    ("How do you create a function in JavaScript?", [
        ("function = myFunction()", True),
        ("function: myFunction()", False),
        ("function myFunction()", False),
        ("myFunction() function", False),
    ]),
    ("How do you call a function named 'myFunction'?", [
        ("myFunction()", True),
        ("call function myFunction()", False),
        ("call myFunction()", False),
        ("run myFunction()", False),
    ]),
    ("How do you write an IF statement in JavaScript?", [
        ("if i == 5 then", True),
        ("if (i == 5)", False),
        ("if i = 5 then", False),
        ("if i = 5", False),
    ]),
    ("How can you add a comment in a JavaScript?", [
        ("<!--This is a comment-->", True),
        ("/*This is a comment*/", False),
        ("//This is a comment", False),
        ("#This is a comment", False),
    ]),
    ("How to insert a JavaScript into an HTML page?", [
        ("<script>", True),
        ("<script src='myscript.js'>", False),
        ("<javascript>", False),
        ("All of the above", False),
    ]),
    ("What is the correct place to insert a JavaScript?", [
        ("Both the <head> section and the <body> section are correct", True),
        ("The <head> section", False),
        ("The <body> section", False),
        ("None of the above", False),
    ]),
    ("What is the correct syntax for an if statement in JavaScript?", [
        ("if i = 5 then", True),
        ("if (i == 5)", False),
        ("if i == 5", False),
        ("if i == 5 then", False),
    ]),
    ("Which operator is used to assign a value to a variable?", [
        ("x = 5", True),
        ("x == 5", False),
        ("x === 5", False),
        ("x != 5", False),
    ]),
    ("What will the following code return? Boolean(10 > 9)", [
        ("true", True),
        ("false", False),
        ("NaN", False),
        ("undefined", False),
    ]),
    ("Which of the following is not a reserved word in JavaScript?", [
        ("interface", True),
        ("function", False),
        ("throw", False),
        ("default", False),
    ]),
    ("How do you round the number 7.25, to the nearest integer?", [
        ("Math.round(7.25)", True),
        ("Math.ceil(7.25)", False),
        ("Math.floor(7.25)", False),
        ("Math.round(7.5)", False),
    ]),
    ("JavaScript is the same as Java.", [
        ("False", True),
        ("True", False),
        ("Depends on the browser", False),
        ("Only in some cases", False),
    ]),
    ("How do you declare a JavaScript variable?", [
        ("var x;", True),
        ("let x;", False),
        ("const x;", False),
        ("All of the above", False),
    ]),
    ("Which of the following is a correct way to declare a variable in JavaScript?", [
        ("var x;", True),
        ("let x;", False),
        ("const x;", False),
        ("All of the above", False),
    ]),
    ("How do you create an object in JavaScript?", [
        ("var obj = {}", True),
        ("var obj = ()", False),
        ("var obj = []", False),
        ("var obj = new Object", False),
    ]),
    ("What is the correct syntax for adding comments in JavaScript?", [
        ("//This is a comment", True),
        ("/*This is a comment*/", False),
        ("<!--This is a comment-->", False),
        ("All of the above", False),
    ]),
    ("Which of the following is not a data type in JavaScript?", [
        ("String", True),
        ("Number", False),
        ("Boolean", False),
        ("Alert", False),
    ]),
    ("How do you find the number with the highest value of x and y?", [
        ("Math.max(x, y)", True),
        ("Math.ceil(x, y)", False),
        ("Math.min(x, y)", False),
        ("Math.round(x, y)", False),
    ]),
    ("Where is the correct place to insert a JavaScript?", [
        ("Both the <head> section and the <body> section are correct", True),
        ("The <head> section", False),
        ("The <body> section", False),
        ("None of the above", False),
    ]),
    ("How do you write 'Hello World' in an alert box?", [
        ("alert('Hello World')", True),
        ("msg('Hello World')", False),
        ("msgBox('Hello World')", False),
        ("alertBox('Hello World')", False),
    ]),
    ("How do you create a function in JavaScript?", [
        ("function myFunction()", True),
        ("function: myFunction()", False),
        ("function = myFunction()", False),
        ("myFunction() function", False),
    ]),
    ("How to write an IF statement in JavaScript?", [
        ("if (i == 5)", True),
        ("if i == 5 then", False),
        ("if i = 5 then", False),
        ("if i = 5", False),
    ]),
    ("How can you add a comment in a JavaScript?", [
        ("//This is a comment", True),
        ("<!--This is a comment-->", False),
        ("/*This is a comment*/", False),
        ("#This is a comment", False),
    ]),
    ("Is JavaScript case-sensitive?", [
        ("Yes", True),
        ("No", False),
        ("Only for variables", False),
        ("Only for functions", False),
    ]),
    ("Which of the following is the correct syntax to print 'Hello World' in JavaScript?", [
        ("console.log('Hello World')", True),
        ("print('Hello World')", False),
        ("echo('Hello World')", False),
        ("log('Hello World')", False),
    ]),
    ("What is the use of isNaN function?", [
        ("To check if a value is NaN", True),
        ("To check if a value is a number", False),
        ("To convert a string to number", False),
        ("To check if a value is null", False),
    ]),
    ("Which of the following is a server-side JavaScript object?", [
        ("Function", True),
        ("File", False),
        ("Date", False),
        ("Array", False),
    ]),
    ("Inside which HTML element do we put the JavaScript?", [
        ("<script>", True),
        ("<javascript>", False),
        ("<js>", False),
        ("<scripting>", False),
    ]),
    ("What is the correct syntax for adding a new property to an object?", [
        ("object.property = value", True),
        ("object.add(property, value)", False),
        ("object.new(property, value)", False),
        ("object.set(property, value)", False),
    ]),
    ("How do you check if a variable is an array?", [
        ("Array.isArray(variable)", True),
        ("variable instanceof Array", False),
        ("typeof variable == 'array'", False),
        ("All of the above", False),
    ]),
    ("What is the output of typeof null?", [
        ("object", True),
        ("null", False),
        ("undefined", False),
        ("string", False),
    ]),
    ("Which method is used to join two or more arrays?", [
        ("concat()", True),
        ("join()", False),
        ("push()", False),
        ("splice()", False),
    ]),
    ("How do you add an element to the end of an array?", [
        ("push()", True),
        ("pop()", False),
        ("shift()", False),
        ("unshift()", False),
    ]),
    ("What does the 'this' keyword refer to?", [
        ("The current object", True),
        ("The global object", False),
        ("The parent object", False),
        ("The child object", False),
    ]),
    ("Which event occurs when the user clicks on an HTML element?", [
        ("onclick", True),
        ("onmouseclick", False),
        ("onmouseover", False),
        ("onclickevent", False),
    ]),
    ("How do you get the length of a string?", [
        ("string.length", True),
        ("string.size", False),
        ("string.len", False),
        ("length(string)", False),
    ]),
    ("What is the correct way to write a JSON object?", [
        ("{'name': 'John', 'age': 30}", True),
        ("{name: 'John', age: 30}", False),
        ("{name = 'John', age = 30}", False),
        ("name: 'John', age: 30", False),
    ]),
    ("Which method is used to convert JSON string to JavaScript object?", [
        ("JSON.parse()", True),
        ("JSON.stringify()", False),
        ("JSON.toObject()", False),
        ("parseJSON()", False),
    ]),
    ("What is the purpose of the 'async' keyword in a function?", [
        ("To make the function asynchronous", True),
        ("To make the function synchronous", False),
        ("To pause the function", False),
        ("To run the function in parallel", False),
    ]),
    ("How do you handle errors in JavaScript?", [
        ("try...catch", True),
        ("if...else", False),
        ("switch", False),
        ("while", False),
    ]),
    ("What is a closure in JavaScript?", [
        ("A function that has access to its outer scope", True),
        ("A way to hide variables", False),
        ("A type of loop", False),
        ("A method to close functions", False),
    ]),
    ("Which method is used to remove the last element from an array?", [
        ("pop()", True),
        ("push()", False),
        ("shift()", False),
        ("unshift()", False),
    ]),
    ("What is the default value of a variable declared with 'var' if not initialized?", [
        ("undefined", True),
        ("null", False),
        ("0", False),
        ("''", False),
    ]),
    ("How do you create a promise in JavaScript?", [
        ("new Promise()", True),
        ("Promise.create()", False),
        ("createPromise()", False),
        ("Promise.new()", False),
    ]),
    ("What does the '=== ' operator do?", [
        ("Strict equality comparison", True),
        ("Assignment", False),
        ("Loose equality", False),
        ("Not equal", False),
    ]),
    ("Which global object provides access to the browser's URL?", [
        ("window.location", True),
        ("document.URL", False),
        ("navigator.url", False),
        ("browser.location", False),
    ]),
    ("How do you select an element by ID in the DOM?", [
        ("document.getElementById('id')", True),
        ("document.getElement('id')", False),
        ("elementById('id')", False),
        ("select('#id')", False),
    ]),
    ("What is the purpose of 'localStorage'?", [
        ("To store data locally in the browser", True),
        ("To store data on the server", False),
        ("To cache images", False),
        ("To manage cookies", False),
    ]),
    ("Which method is used to prevent default behavior of an event?", [
        ("preventDefault()", True),
        ("stopPropagation()", False),
        ("stopDefault()", False),
        ("cancelEvent()", False),
    ]),
    ("What is hoisting in JavaScript?", [
        ("Moving declarations to the top of the scope", True),
        ("A way to lift elements", False),
        ("A type of loop", False),
        ("A debugging tool", False),
    ]),
    ("How do you iterate over an object’s properties?", [
        ("for...in", True),
        ("for...of", False),
        ("forEach()", False),
        ("map()", False),
    ]),
    ("What is the output of console.log(0.1 + 0.2 == 0.3)?", [
        ("false", True),
        ("true", False),
        ("0.3", False),
        ("undefined", False),
    ]),
    ("Which method is used to convert a number to a string?", [
        ("toString()", True),
        ("parseInt()", False),
        ("Number()", False),
        ("String()", False),
    ]),
    ("What is the difference between 'null' and 'undefined'?", [
        ("null is assigned, undefined is default", True),
        ("They are the same", False),
        ("null is for objects, undefined for primitives", False),
        ("undefined is for null values", False),
    ]),
    ("How do you debounce a function?", [
        ("Using setTimeout inside the function", True),
        ("Using setInterval", False),
        ("Using requestAnimationFrame", False),
        ("Using async/await", False),
    ]),
    ("What is event bubbling?", [
        ("Events propagating from child to parent", True),
        ("Events propagating from parent to child", False),
        ("Events stopping at the target", False),
        ("Events being ignored", False),
    ]),
    ("Which method is used to add an event listener?", [
        ("addEventListener()", True),
        ("onEvent()", False),
        ("attachEvent()", False),
        ("bindEvent()", False),
    ]),
    ("What is the purpose of 'JSON.stringify()'? ", [
        ("To convert JS object to JSON string", True),
        ("To parse JSON", False),
        ("To validate JSON", False),
        ("To minify JSON", False),
    ]),
    ("How do you check if a key exists in an object?", [
        ("'key' in object", True),
        ("object.hasKey('key')", False),
        ("object.contains('key')", False),
        ("object.key exists", False),
    ]),
    ("What is a callback function?", [
        ("A function passed as an argument to another function", True),
        ("A function that calls itself", False),
        ("A function that returns another function", False),
        ("A synchronous function", False),
    ]),
    ("Which feature allows running code after the DOM is loaded?", [
        ("DOMContentLoaded", True),
        ("window.onload", False),
        ("document.ready", False),
        ("loadEvent", False),
    ]),
    ("What is the 'let' keyword used for?", [
        ("Block-scoped variable declaration", True),
        ("Global variable", False),
        ("Constant", False),
        ("Function declaration", False),
    ]),
    ("How do you remove a property from an object?", [
        ("delete object.property", True),
        ("object.remove('property')", False),
        ("object.delete(property)", False),
        ("remove object.property", False),
    ]),
    ("What is the purpose of 'setTimeout()'? ", [
        ("To execute code after a delay", True),
        ("To execute code repeatedly", False),
        ("To stop execution", False),
        ("To measure time", False),
    ]),
    ("Which method is used to sort an array?", [
        ("sort()", True),
        ("order()", False),
        ("arrange()", False),
        ("reverse()", False),
    ]),
    ("What does 'NaN' stand for?", [
        ("Not a Number", True),
        ("No available number", False),
        ("Null and Number", False),
        ("Not any Number", False),
    ]),
    ("How do you create a deep copy of an object?", [
        ("JSON.parse(JSON.stringify(obj))", True),
        ("Object.assign({}, obj)", False),
        ("obj.clone()", False),
        ("new Object(obj)", False),
    ]),
    ("What is prototypal inheritance?", [
        ("Objects inheriting from other objects", True),
        ("Classes inheriting from classes", False),
        ("Functions inheriting properties", False),
        ("Variables inheriting values", False),
    ]),
    ("Which method is used to merge two objects?", [
        ("Object.assign()", True),
        ("Object.merge()", False),
        ("obj1 + obj2", False),
        ("combine(obj1, obj2)", False),
    ]),
    ("What is the output of [] + []?", [
        ("''", True),
        ("[]", False),
        ("undefined", False),
        ("null", False),
    ]),
    ("How do you stop event propagation?", [
        ("stopPropagation()", True),
        ("preventDefault()", False),
        ("stopEvent()", False),
        ("cancelBubble()", False),
    ]),
    ("What is an IIFE?", [
        ("Immediately Invoked Function Expression", True),
        ("Inline Invoked Function Execution", False),
        ("Immediate Function Invocation", False),
        ("Isolated Function Execution", False),
    ]),
    ("Which keyword is used for classes in ES6?", [
        ("class", True),
        ("function", False),
        ("object", False),
        ("new", False),
    ]),
    ("What is the purpose of 'async/await'?", [
        ("To handle asynchronous code synchronously", True),
        ("To make code faster", False),
        ("To pause execution", False),
        ("To create promises", False),
    ]),
    ("How do you get the current timestamp?", [
        ("Date.now()", True),
        ("new Date().getTime()", False),
        ("timestamp()", False),
        ("time.now()", False),
    ]),
    ("What is currying in JavaScript?", [
        ("Transforming a function with multiple arguments into nested functions", True),
        ("A way to curry food", False),
        ("A type of loop", False),
        ("A debugging method", False),
    ]),
    ("Which method is used to filter an array?", [
        ("filter()", True),
        ("map()", False),
        ("reduce()", False),
        ("forEach()", False),
    ]),
    ("What is the 'const' keyword used for?", [
        ("Block-scoped constant declaration", True),
        ("Global constant", False),
        ("Variable declaration", False),
        ("Function declaration", False),
    ]),
    ("How do you reverse a string?", [
        ("string.split('').reverse().join('')", True),
        ("string.reverse()", False),
        ("reverse(string)", False),
        ("string.invert()", False),
    ]),
    ("What is memoization?", [
        ("Caching results of expensive function calls", True),
        ("A way to remember variables", False),
        ("A type of loop", False),
        ("A debugging tool", False),
    ]),
    ("Which method is used to find the index of an element in an array?", [
        ("indexOf()", True),
        ("findIndex()", False),
        ("position()", False),
        ("locate()", False),
    ]),
    ("What is the difference between '==' and '==='?", [
        ("== is loose equality, === is strict", True),
        ("They are the same", False),
        ("== checks type, === doesn't", False),
        ("=== is loose", False),
    ]),
    ("How do you destructure an array?", [
        ("const [a, b] = arr", True),
        ("const {a, b} = arr", False),
        ("destructure arr", False),
        ("arr.unpack(a, b)", False),
    ]),
    ("What is a generator function?", [
        ("A function that can pause and resume execution", True),
        ("A function that generates numbers", False),
        ("A synchronous function", False),
        ("A recursive function", False),
    ]),
    ("Which method is used to reduce an array to a single value?", [
        ("reduce()", True),
        ("map()", False),
        ("filter()", False),
        ("forEach()", False),
    ]),
    ("What is the purpose of 'bind()' method?", [
        ("To set the 'this' context of a function", True),
        ("To call a function", False),
        ("To apply arguments", False),
        ("To create a new function", False),
    ]),
    ("How do you check if a variable is null?", [
        ("variable === null", True),
        ("variable == null", False),
        ("typeof variable === 'null'", False),
        ("isNull(variable)", False),
    ]),
    ("What is the 'spread operator' used for?", [
        ("To expand elements of an array or object", True),
        ("To create a new array", False),
        ("To merge arrays", False),
        ("To copy objects", False),
    ]),
    ("Which event is fired when a form is submitted?", [
        ("submit", True),
        ("onsubmit", False),
        ("formsubmit", False),
        ("send", False),
    ]),
    ("What is the output of typeof NaN?", [
        ("number", True),
        ("nan", False),
        ("undefined", False),
        ("object", False),
    ]),
    ("How do you create a Set in JavaScript?", [
        ("new Set()", True),
        ("Set.create()", False),
        ("{}", False),
        ("[]", False),
    ]),
    ("What is the purpose of 'Map' object?", [
        ("To store key-value pairs where keys can be any type", True),
        ("To store unique values", False),
        ("To store ordered lists", False),
        ("To store functions", False),
    ]),
    ("Which method is used to execute a function for each array element?", [
        ("forEach()", True),
        ("map()", False),
        ("filter()", False),
        ("reduce()", False),
    ]),
    ("What is a WeakMap?", [
        ("A Map where keys must be objects and are weakly referenced", True),
        ("A Map with weak values", False),
        ("A small Map", False),
        ("A Map for weak types", False),
    ]),
    ("How do you import a module in ES6?", [
        ("import {func} from 'module'", True),
        ("require('module')", False),
        ("include 'module'", False),
        ("load 'module'", False),
    ]),
    ("What is the 'default export' in modules?", [
        ("The main export of a module", True),
        ("An optional export", False),
        ("A named export", False),
        ("An import statement", False),
    ]),
    ("Which method is used to convert arguments to an array?", [
        ("Array.from(arguments)", True),
        ("arguments.toArray()", False),
        ("[].slice.call(arguments)", False),
        ("Array(arguments)", False),
    ]),
    ("What is tail call optimization?", [
        ("Optimizing recursive calls by reusing the current stack frame", True),
        ("Optimizing loops", False),
        ("Optimizing async calls", False),
        ("Optimizing object creation", False),
    ]),
    ("How do you implement private variables in ES6?", [
        ("Using symbols or WeakMaps", True),
        ("Using var _private", False),
        ("Using private keyword", False),
        ("Using #private", False),
    ]),
    ("What is the purpose of 'Proxy' object?", [
        ("To define custom behavior for fundamental operations", True),
        ("To create proxies for functions", False),
        ("To handle HTTP requests", False),
        ("To manage network connections", False),
    ]),
    ("Which method is used to get the prototype of an object?", [
        ("Object.getPrototypeOf()", True),
        ("obj.prototype", False),
        ("getProto(obj)", False),
        ("prototypeOf(obj)", False),
    ]),
    ("What is 'Symbol' used for?", [
        ("To create unique identifiers", True),
        ("To symbolize functions", False),
        ("To create symbols in math", False),
        ("To represent variables", False),
    ]),
    ("How do you define a getter in an object?", [
        ("get property() {}", True),
        ("getter property {}", False),
        ("property: get {}", False),
        ("defineGetter('property', fn)", False),
    ]),
    ("What is the 'Reflect' object for?", [
        ("To perform operations on objects in a functional way", True),
        ("To reflect changes", False),
        ("To mirror objects", False),
        ("To introspect code", False),
    ]),
    ("Which feature allows optional chaining?", [
        ("obj?.property", True),
        ("obj.property || default", False),
        ("if (obj.property)", False),
        ("obj.get('property')", False),
    ]),
    ("What is a rest parameter?", [
        ("...args to collect remaining arguments", True),
        ("A parameter that rests", False),
        ("A default parameter", False),
        ("An optional parameter", False),
    ]),
    ("How do you use template literals?", [
        ("`Hello ${name}`", True),
        ("'Hello ' + name", False),
        ("\"Hello #{name}\"", False),
        ("Hello {name}", False),
    ]),
    ("What is the purpose of 'BigInt'?", [
        ("To represent integers larger than Number.MAX_SAFE_INTEGER", True),
        ("To handle big data", False),
        ("To perform big calculations", False),
        ("To store large numbers", False),
    ]),
    ("Which method is used to pad a string?", [
        ("padStart() or padEnd()", True),
        ("pad()", False),
        ("stringPad()", False),
        ("fill()", False),
    ]),
    ("What is 'includes()' method for strings?", [
        ("To check if a string contains a substring", True),
        ("To include a file", False),
        ("To add to an array", False),
        ("To check array membership", False),
    ]),
    ("How do you use the nullish coalescing operator?", [
        ("value ?? default", True),
        ("value || default", False),
        ("value != null ? value : default", False),
        ("if (value) value else default", False),
    ]),
    ("What is logical assignment operator?", [
        ("x ||= y for OR", True),
        ("x = x || y", False),
        ("assign(x, y)", False),
        ("x or= y", False),
    ]),
    ("Which API is used for top-level await?", [
        ("ES2022 modules", True),
        ("Async functions", False),
        ("Promises", False),
        ("setTimeout", False),
    ]),
    ("What is private fields in classes?", [
        ("#field for private properties", True),
        ("private field", False),
        ("var _field", False),
        ("this._field", False),
    ]),
    ("How do you use dynamic import?", [
        ("import('./module.js')", True),
        ("require('./module.js')", False),
        ("load('./module.js')", False),
        ("dynamic require", False),
    ]),
    ("What is the 'for await...of' loop for?", [
        ("Iterating over async iterables", True),
        ("Synchronous loops", False),
        ("Promise chains", False),
        ("Array iteration", False),
    ]),
    ("Which method is used for array flat?", [
        ("flat()", True),
        ("flatten()", False),
        ("reduce(flatten)", False),
        ("join().split()", False),
    ]),
    ("What is 'Object.fromEntries()'? ", [
        ("To create object from key-value pairs", True),
        ("To get entries", False),
        ("To merge objects", False),
        ("To convert to array", False),
    ]),
    ("How do you use 'String.prototype.matchAll()'? ", [
        ("string.matchAll(regex)", True),
        ("matchAll(string, regex)", False),
        ("regex.matchAll(string)", False),
        ("allMatches(string, regex)", False),
    ]),
    ("What is 'Promise.allSettled()'? ", [
        ("Wait for all promises to settle", True),
        ("All promises to resolve", False),
        ("One promise to settle", False),
        ("Promises to reject", False),
    ]),
    ("Which feature is 'globalThis'?", [
        ("Global object across environments", True),
        ("Global variables", False),
        ("This in global scope", False),
        ("Global functions", False),
    ]),
    ("What is 'String.prototype.replaceAll()'? ", [
        ("Replace all occurrences", True),
        ("replace with all", False),
        ("global replace", False),
        ("replace(/g)", False),
    ]),
    ("How do you use numeric separators?", [
        ("1_000_000", True),
        ("1000000", False),
        ("1,000,000", False),
        ("1000.000", False),
    ]),
    ("What is 'import.meta'?", [
        ("Meta information about the module", True),
        ("Import metadata", False),
        ("Module meta", False),
        ("Meta import", False),
    ]),
    ("Which method is 'Array.prototype.at()'? ", [
        ("Access element by index, negative for end", True),
        ("at index", False),
        ("getAt()", False),
        ("elementAt()", False),
    ]),
    ("What is 'Object.hasOwn()'?", [
        ("Check if object has own property", True),
        ("has own property", False),
        ("ownProperty()", False),
        ("hasOwnProperty()", False),
    ]),
    ("How do you use '???' for logical nullish?", [
        ("Not standard yet", True),
        ("x ?? y ?? z", False),
        ("nullish OR", False),
        ("coalesce", False),
    ]),
    ("What is 'Error.cause'?", [
        ("Cause of the error", True),
        ("Error cause", False),
        ("throw cause", False),
        ("new Error(cause)", False),
    ]),
    ("Which is 'ArrayBuffer.prototype.transfer()'? ", [
        ("Transfer ownership of buffer", True),
        ("transfer buffer", False),
        ("move buffer", False),
        ("detach buffer", False),
    ]),
    ("What is 'RegExp.prototype.exec() improved'? ", [
        ("Sticky flag support", True),
        ("exec with sticky", False),
        ("global exec", False),
        ("match exec", False),
    ]),
    ("How do you use 'for...in with prototypes'? ", [
        ("Includes prototypes", True),
        ("Only own properties", False),
        ("Enumerable only", False),
        ("All properties", False),
    ]),
    ("What is the final count for JEE questions? Wait, this is JS.", [
        ("100", True),
        ("50", False),
        ("200", False),
        ("75", False),
    ]),
]


class Command(BaseCommand):
    help = 'Seed 100 JavaScript-related questions into the quiz app (idempotent)'

    def handle(self, *args, **options):
        created = 0
        js_subj, _ = Subject.objects.get_or_create(name='JavaScript')
        # Remove existing JavaScript questions
        Question.objects.filter(subject=js_subj).delete()
        for q_text, choices in QUESTIONS:
            q = Question.objects.create(text=q_text, subject=js_subj)
            created += 1
            # create choices
            for choice_text, is_correct in choices:
                Choice.objects.create(question=q, text=choice_text, is_correct=is_correct)
        self.stdout.write(self.style.SUCCESS(f'Successfully seeded {created} JavaScript questions.'))
