# Generated by Django 4.2.25 on 2025-10-08 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_subject_question_category_question_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
    ]
